### ISSUE TITLE
Redirect all HTTP to HTTPS

### ISSUE THREAD

**Issue by shawticus** [XRFoundation/XREngine#1050]
Right now on local dev, going to http://localhost:3000 will show nothing, which looks like something is wrong. Redirect it to HTTPS so it always works, even if dev tries http

┆Issue is synchronized with this [Jira Task](https://laguna.atlassian.net/browse/XR3NGIN-14) by [Unito](https://www.unito.io/learn-more)

**Comment by tarasprystavskyj** [comment]
Sergiy sais: 
"You can start the HTTP server on port 80 and HTTPS on port 443. Then redirection is possible and the port in the address does not need to be specified."

So I see two ways 
or to do this. I suppose we can not do this automaticaly without developer help just changind the code. 
than just changing http to https manualy every time is faster solution. 
I proposed a task for Bohdan to start creating onboarding document of instrucations. We can add this point to the document as quick fix for now.
