### ISSUE TITLE
Replace three base types with math.gl and isolate three.js to rendering and scene binding

### ISSUE THREAD

**Issue by shawwwwwwww** [XRFoundation/XREngine#1350]
The three.js vector, quaternion and matrix types are friendly and easy to use but not performant. When upgrading to bitECS/threecs we should upgrade these as well.

**Comment by HexaField** [comment]
We may no longer need math.gl as recent v8 optimisation have made the difference negligible. We may need to do some benchmarks to see if this is still necessary.
