### ISSUE TITLE
User inventory and item management

### ISSUE THREAD

**Issue by shawwwwwwww** [XRFoundation/XREngine#1399]
We want users to be able to upload 3D models and other files.

@kinjalravel  has been doing this somewhat with the file browser

The next step is to build this into a full inventory. That means users can look at all the items in their inventory in the /editor , but also we will expose a menu component to the front end so they can persist items into the world (eventually).

For now, inventory will hold 3D assets, avatars, any kind of asset pack or data pack we want.

**Comment by NateTheGreatt** [comment]
duplicate
https://github.com/XRFoundation/XREngine/issues/294
