### ISSUE TITLE
Update post processing & test in XR

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#1858]
Our post processing pipeline uses the postprocessing library for threejs, it is outdated and has no guarantee of working XR

- [x] replace postprocessing code with npm package
- [ ] patch postprocessing to work in VR

**Comment by mrhegemon** [comment]
https://github.com/vanruesc/postprocessing

**Comment by shawwwwwwww** [comment]
@HexaField without single pass stereo instanced rendering, even on high end hardware we are talking about massive frame hits. Postprocessing library we are using out of the box won't support WebXR, and we would absolutely want it disabled for quest users anyways, so my thought is that we just close this issue and XR = no post processing for now
