### ISSUE TITLE
Immutable.js -> Hookstate 

### ISSUE THREAD

**Issue by speigg** [XRFoundation/XREngine#2088]
Switch to ~Immer~ [hookstate](https://hookstate.js.org)  for better typing and ease of development.

**Comment by kinjalravel** [comment]
@shawwwwwwww Did you mean this right? https://immerjs.github.io/immer/

**Comment by shawwwwwwww** [comment]
Yes exactly

**Comment by speigg** [comment]
@kinjalravel  have you started working on this? I want to use hook-state instead, as it has a cleaner api and is more performant & less garbage producing than immutable stores. Still want to keep the redux pattern of action-creators and dispatch.

**Comment by NateTheGreatt** [comment]
great work @kinjalravel !
