### ISSUE TITLE
Redux connect() -> hooks

### ISSUE THREAD

**Issue by speigg** [XRFoundation/XREngine#2089]
Switch from Redux connect() API to Redux hooks for better typing.

**Comment by shawwwwwwww** [comment]
Assigning @thanhhovn2016  -- please check in with @speigg if you have any questions about best way to implement this task.

**Comment by speigg** [comment]
I think @kinjalravel is already working on refactoring the data store, and that would conflict with this 

@thanhhovn2016 lets start you off with this issue [](https://github.com/XRFoundation/XREngine/issues/2982)
