### ISSUE TITLE
Render tonemapping / shadowmaps

### ISSUE THREAD

**Issue by Bluepulasky** [XRFoundation/XREngine#2158]
On 

https://github.com/XRFoundation/XREngine/blob/dev/packages/engine/src/renderer/WebGLRendererSystem.ts

lines 161 and 162:
renderer.toneMapping = LinearToneMapping; 
renderer.toneMappingExposure = 0.8

Kindly request that both of this parameters could be able to be changed on the editor to fine tune the look of each scene.

Also check line 173. Does this fixed value cause shadow clipping on some scenes if they are really big?

**Comment by HexaField** [comment]
Thanks for making the issue! Looks like I have already implemented this. These settings can be found on the root Scene Node in the editor if you check 'Override Renderer Settings'
