### ISSUE TITLE
Editor > Publish Button > Should only be able to publish current scene

### ISSUE THREAD

**Issue by shawwwwwwww** [XRFoundation/XREngine#2364]
Right now Publish is showing the publish dialog. This is fine, but the publish dialog should have an option to lock the scene and force it to be the current one, so that when users go to publish 1. the scene is actually there already and 2. they can't accidentally change it.

Users should still be able to publish scenes arbitrarily from outside of the scene editor view.

**Comment by kimenyikevin** [comment]
Fixed and PR was merged

**Comment by shawwwwwwww** [comment]
@kimenyikevin not seeing it, please review screenshot

![Screenshot from 2021-07-17 01-41-18](https://user-images.githubusercontent.com/18633264/126031538-59da8fb2-5764-4222-b00f-d723db479795.png)
