### ISSUE TITLE
Twitch stream

### ISSUE THREAD

**Issue by lalalune** [XRFoundation/XREngine#2401]
We want to be able to add Twitch streams to worlds like other videos.

@HexaField and @speigg have already reviewed the problem and have some ideas on how to solve it. Might already be mostly there.

https://github.com/BernardJeremy/node-twitch-link
https://github.com/nicholastay/node-twitch-get-stream
https://github.com/warren-bank/HLS-Proxy

We need to proxy twitch through our gameserver and stream it onto a 3D object. Because of CORS restrictions we can't do this in VR without using a proxy.

1. Go to https://localhost:3000/editor - a. create a new project, b. ctrl s to save the project, c. create a new location, with that project set for the location
2. Go to https://localhost:3000/location/<locationName> -- this is where you can see it
3. Go back to your project in the editor and add a video object and add a URL to a twitch stream
4. Go back to your location -- probably doesn't work.

So we need to add a proxy to our app in server package. In the loader for the video node in the client, we need to check for twitch in the URL, and request through the proxy using CORS anywhere instead.

Here is some code for the CORS proxy

const express = require('express')
const corsAnywhere = require("cors-anywhere")
const dotenv = require('dotenv')
dotenv.config()

const host = '0.0.0.0'
const port = 9000

// proxy
const proxy = corsAnywhere
  .createServer({
    originWhitelist: [],
    requireHeader: ['Origin'],
    removeHeaders: [],
  })
  .listen(port + 1, host, () => {
    console.log(`Running CORS Anywhere on ${port + 1}`)
  })

// express
const app = express()
app.get('/twitch/*', function(req, res) {
  req.url = req.url.replace('/twitch', '/https://api.twitch.tv/helix')
  req.headers['Authorization'] = `Bearer ${process.env.TWITCH_TOKEN}`
  req.headers['Client-Id'] = process.env.TWITCH_CLIENT_ID
  proxy.emit('request', req, res)
})

**Comment by HexaField** [comment]
Twitch prevents accessing the raw video feed from their API due to iframe restrictions, so we will need to create a proxy through our backend. This is what hubs appears to do.

**Comment by NavdeepYadavskylight** [comment]
I have made the changes in videonode to check if the url. include('twitch.tv') than it makes a server call to get the url and assigned url back to src of video
