### ISSUE TITLE
Post Processing settings are not properly ranged for SSAO in editor

### ISSUE THREAD

**Issue by shawwwwwwww** [XRFoundation/XREngine#2440]
The post processing settings aren't a perfect fit. "Samples" is an int between 1 and 64, with a default to 16, but is treated as a float with a range of 0-1. Etc etc. Needs to be fixed.

![Screenshot from 2021-07-14 01-53-02](https://user-images.githubusercontent.com/18633264/125593606-9bf81e06-3118-471f-a827-9c412cda3c08.png)

**Comment by shawwwwwwww** [comment]
![Screenshot from 2021-07-14 01-54-44](https://user-images.githubusercontent.com/18633264/125593872-d44cbba8-282f-4a0a-bff5-50073500f24d.png)

**Comment by Abhishek-Pathak-Here** [comment]
@kimenyikevin 
You can tweak these settings from PostProcessingNodeEditor.
In EffectsOptions object there are min/max/step parameters.
You can tweak those.

**Comment by kimenyikevin** [comment]
@shawwwwwwww  I have fixed the issue, here is [PR](https://github.com/XRFoundation/XREngine/pull/2457)
