### ISSUE TITLE
[Story] UVOL prefab updates - playlist, collideable trigger, seek, loop

### ISSUE THREAD

**Issue by mrhegemon** [XRFoundation/XREngine#2459]
We want a playlist feature where we can set up many uvol captures to play in a row.
we have several bugs with it looping improperly with audio.

We want to trigger certain other things to happen when a user steps on a trigger.
Specifically, a trigger should be able to:
1. play an animation (or volumetric capture) when user enters
2. play an animation (or volumetric capture) when user leaves
3. play an animation (or volumetric capture) while user is in

we need to track the video playback frames and sync them to the frames coming from the manifest. This is read by the worker for corto 3d decompression and render, we need to make sure this is all handled cleanly with play/pause sync on the time codes to 3d frames.

once we have playback wrapped well, we can focus on making better playlist, replay, looping, and seek features to the player.

This is similar to a trigger volume in Unity. However, we want to be able to do this in the editor, and set the target to other objects -- specifically "Model" nodes and Volumetric nodes. So it would be the equivalent of referencing another game object in the inspector.

Our editor is here:
https://dev.theoverlay.io/editor

Volumetric capture looks like this:
https://wildcapture.io/ohno.html

The volumetric component is available in the editor. Please ask team (shaw, liam, or WillD) for a uvol file to work with

We've done a similar thing for "material override" on the model.

- [x] playlist
- [x] trigger
- [x] loop
- [x] seek

**Comment by shawwwwwwww** [comment]
I have made a PR that starts to flesh this out, and it is set up in editor but not yet fully in engine.
