### ISSUE TITLE
Redesign chat, chat window should be "open" when a user joins

### ISSUE THREAD

**Issue by shawwwwwwww** [XRFoundation/XREngine#2647]
Right now, chat is not obvious, and it's not designed terribly well.

Please look at the following:
http://spatial.io (try logging in and going through the flow, this is the best app that is similar to ours)
https://vesta.janusxr.org/spyduck/lains-bedroom-serial-experiments-lain (another similar project/app)

We should make our design better and cleaner.

Also, we should start expanded, so any chat is revealed to users

![image](https://user-images.githubusercontent.com/18633264/128124843-62f298e8-9df5-464c-9d1e-0d0ce1fcdb75.png)

Ours, but open:
![image](https://user-images.githubusercontent.com/18633264/128131007-d149e3d4-f130-4f45-8e7b-b3c462c5016e.png)

**Comment by NateTheGreatt** [comment]
@shawwwwwwww @kinjalravel

does #2978 satisfy this issue as a whole, or do other issues need to be created to finish this off?
