### ISSUE TITLE
QA running, fix walking issues

### ISSUE THREAD

**Issue by shawwwwwwww** [XRFoundation/XREngine#2751]
Right now, running seems to blend okay, but walking doesn't. It's not clear why. They should loop perfectly.

Something to do with keeping the animations in sync, perhaps?

To reproduce:
Try running around. A little hiccup from idle into run, but otherwise loops well.
Now hold shit and move to walk around. Doesn't seem to loop properly.

Added a to-do to line 78 of; AnimationRenderer.ts
![image](https://user-images.githubusercontent.com/18633264/129010486-7626b3e5-2b38-4b24-b6bb-ead516966415.png)

**Comment by NateTheGreatt** [comment]
behavior not reproducible, seems fixed
