### ISSUE TITLE
ThirdPerson is not handled by CameraSystem

### ISSUE THREAD

**Issue by XiaNi** [XRFoundation/XREngine#2834]
CameraMode.ThirdPerson is not handled by followCameraBehavior in CameraSystem that leads to broken camera transform.
following error is caused by this:
```
Uncaught TypeError: Failed to execute 'linearRampToValueAtTime' on 'AudioParam': The provided float value is non-finite.
    at AudioListener.updateMatrixWorld (three.module.js:42452)
    at PerspectiveCamera.updateMatrixWorld (three.module.js:7060)
    at PerspectiveCamera.updateMatrixWorld (three.module.js:11405)
    at CameraSystem.ts:259
    at AnonymousSystem_internal (System.js:18)
    at index.js:21
    at Object.update (initializeEngine.ts:279)
    at onFrame (Timer.ts:130)
```

**Comment by XiaNi** [comment]
CameraMode.Dynamic is probably same since there is no usages in followCameraBehavior

**Comment by shawwwwwwww** [comment]
@XiaNi there is still some bugs with this logic, but i fixed the major audio error param issue thrown. Generally this logic could be more thoroughly tested, but now it's working and I'm very tired :)

**Comment by shawwwwwwww** [comment]
@aleksmaz when you are done with other tasks, let's revisit this and try to make sure the camera component is really robust and all the features work with each other
