### ISSUE TITLE
First user is made an admin

### ISSUE THREAD

**Issue by shawwwwwwww** [XRFoundation/XREngine#2967]

**Comment by barankyle** [comment]
Is this to make the first guest user an admin? The first logged-in user is already made an admin.

**Comment by HexaField** [comment]
> Is this to make the first guest user an admin? The first logged-in user is already made an admin.

Oh, the first logged-in user? Does this require oauth or a name change? I imagine it would make more sense to make the first guest user an admin rather than the first logged in user, as reinit happens often and this is an extra step many people may not realise is necessary.

**Comment by barankyle** [comment]
It does require either OAuth, email, or SMS credentials to log in. I can see where the first guest user being made an admin on local makes sense - just have to make sure it only applies to local.
