### ISSUE TITLE
Add a 'submit bug' button

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#2973]
For now, just a button that opens this link in a new tab https://github.com/XRFoundation/XREngine/issues/new?assignees=&labels=%5Bbug%5D&template=bug_report.md&title=%5BBug%5D%3A+

Future potential
- capture browser console log
- capture network info
- capture scene data, game state etc
- capture screenshot
- send in an email to a new email address specified in `client-settings` configurable in the admin panel named `bugReportEmail`

**Comment by mrhegemon** [comment]
Top Left {{ SUBMIT ISSUE }}

**Comment by mrhegemon** [comment]
BitScoop.com/Support


https://docs.google.com/forms/d/e/1FAIpQLSeDSOAGzbDKlgXb4Lsh18AZs9jvu9FLxyneX23pEM1yTbCxHw/viewform

**Comment by mrhegemon** [comment]
Github? https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
