### ISSUE TITLE
Editor resets when a new imported scene is saved

### ISSUE THREAD

**Issue by barankyle** [XRFoundation/XREngine#3014]
Seeing the following behavior:

Creating a new scene
Import .world file, loads in the editor fine.
Do a Save As, save the scene.
All of the components/entities are removed from the editor

If I reload the editor for that scene it's loading fine. It's just a bit weird that it visually appears to clear everything after that initial save.

**Comment by Abhishek-Pathak-Here** [comment]
@HexaField  Created a pull request for this.
Please check.
