### ISSUE TITLE
Upload avatar from URL

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#3079]
Would be great to be able to upload an avatar asset by URL from the 'upload avatar' page

**Comment by kinjalravel** [comment]
@HexaField Let me tell you how exactly it's working at the moment 

Currently Server is generating a signed S3 upload url that client can use to upload avatar 3d model and avatar thumbnail 

So this upload process is happening at the client side not on the server 

Now I can defiantly able to create a new function in client side which takes urls of both 3d model and thumbnail image and download it from there and upload to signed S3 urls 

So signature of new wrapper function will be like functionName(urlOf3dModel,urlOfThubnail) and that wrapper function will download both from urls and then call our current function which required file objects 

@HexaField @shawwwwwwww Do you have any other suggestion ?

**Comment by HexaField** [comment]
So we now have a way to create an account with ready player me, but I couldn't find a way to link an existing profile & avatar. The next best thing would be allowing the user to upload the model via the link that is provided alongside the glb on their profile after they have created an avatar via the website.

We can generate the thumbnail for the model from the model, we have this functionality in the backend already.

**Comment by HexaField** [comment]
This can be done way easier actually, we just need to have an option to paste a URL rather than sourcing the file from disk.
