### ISSUE TITLE
Add respawn button if player is stuck

### ISSUE THREAD

**Issue by shawwwwwwww** [XRFoundation/XREngine#3131]

**Comment by zulqarnainhanif** [comment]
@HexaField the respawn button use to hide on medium screen width if i remember correctly but I fixed it in October while revamping the UI. I have tested this on multiple screen widths the issue isn't there anymore. Can we please close this issue.

**Comment by HexaField** [comment]
The respawn button (bottom left of screen) has been implemented, but currently is broken or been disabled. This needs to be fixed, and a test written to ensure it stays fixed.
