### ISSUE TITLE
Using the arrow keys to move.

### ISSUE THREAD

**Issue by mrhegemon** [XRFoundation/XREngine#3247]
Using the arrow keys to move. 

Left and right are turn left and turn right. 

Forward and back move like W & D. 

Anytime you move with the arrow keys to the camera goes to a predefined third person view and zoom. 

Super simple boomer mode for a five-year-old. I have seen too many people struggle with the controls on desktop.

**Comment by mohsenheydari** [comment]
@mrhegemon I have added the functionality. Please check to see if it works as intended.
