### ISSUE TITLE
Enabling post processing make the editor object gizmo disappear

### ISSUE THREAD

**Issue by OmarVector** [XRFoundation/XREngine#3348]
1. Select Post processing in hierarchy 
2. Set it visible in the scene
3. Observe

What happened:
You wont be able to see the gizmo if you select any other object in the scene.

What is expected:
I should be able to see the gizmo and move/rotate/scale any object.

**Comment by HexaField** [comment]
this will be solved when https://github.com/XRFoundation/XREngine/issues/3139 is implemented
