### ISSUE TITLE
Basic lobby and matchmaking

### ISSUE THREAD

**Issue by shawwwwwwww** [XRFoundation/XREngine#3374]
For golf, basketball and other games on our plate, we need to have a some matchmaking tools.

- [x] #4301
- [ ] #4302

Additionally we need a lobby, where things can happy or with a view that can then change when moving into full game.

**Comment by zulqarnainhanif** [comment]
Added a [PR](https://github.com/puttclub/puttclub/pull/7) in puttclub for main menu. (still work in progress though)

**Comment by XiaNi** [comment]
@shawwwwwwww 
matchmaker side status update:
1. users can request some predefined type of game, wait till there will be enough players for that type and then - gameserver instance is created and they can be redirected onto that instance.

2 and 3 is not implemented

2. private/custom means that player can start it's own instance in "private"/"invisible" mode and then invite by some link?
