### ISSUE TITLE
Issues with the Rift S and XR Engine

### ISSUE THREAD

**Issue by HeadClot** [XRFoundation/XREngine#3519]
- In VR mode with the Rift S the controllers are using the wrong controller models
-  Head position is lower than normal
- L and R Controllers are mapped to the wrong hands

Image below to show what is going on. 

![](https://cdn.discordapp.com/attachments/785379094224437248/893404429196341248/unknown.png)

**Comment by HexaField** [comment]
This is likely how we are threejs assigns the controller IDs, they are switched on various devices, sometimes the same OS (such as between oculus quest 2 devices) without a clear reason.
