### ISSUE TITLE
VRM Avatar Import

### ISSUE THREAD

**Issue by shawwwwwwww** [XRFoundation/XREngine#356]
CONTEXT
Right now we are using characters we exported with a skeleton from the Reallusion pipeline. These avatars have matching animation and support blend shapes. However, adding avatars of different types, or allowing users to upload their own avatars will make managing avatars much more complex.
VRM is a format that is very similar to GLTF/GLB but supports extra data, and normalizes some of the skeleton stuff so our characters become universal. With VRM we can allow users to upload their characters from VRChat, various NFT marketplaces and elsewhere

Some relevant repos:
https://hackmd.io/@XR/avatars
https://github.com/exokitxr/avatars
https://github.com/voidedWarranties/openvtuber2
https://github.com/pixiv/three-vrm

DELIVERABLES:
1. Look at our current avatar loading process with GLTF
2. Look at how Exokit Avatars package is loading VRM avatars
3. Integrate three-vrm package into our app, and add functionality to our engine to load VRM files
4. Test scene that has a VRM file in it with animation.
5. Look into converting our existing characters to VRM -- we will probably need to export from Blender.

**Comment by shawticus** [comment]
Should be supported as part of exokit avatars
