### ISSUE TITLE
Video playback from YouTube is broken in production

### ISSUE THREAD

**Issue by HeadClot** [XRFoundation/XREngine#3566]
Currently in production YouTube video playback is broken at the moment. 
The error I am getting is: "Ensure CORS response header values are valid".

Reproduction steps - 

1. Create a new location and name it. Ensure Video playback is enabled.
2. Add a video component to the scene.  
3. Add a YouTube URL to the Video Component. I used this one for testing -> https://www.youtube.com/watch?v=rqF8wIAuOrI
4. Video will not play.
5. Open the debug log with F12 and see the CORS error.

**Comment by HexaField** [comment]
related issue https://github.com/XRFoundation/XREngine/issues/2401
