### ISSUE TITLE
Fix Gamepad Input

### ISSUE THREAD

**Issue by speigg** [XRFoundation/XREngine#3621]

**Comment by rondoor124** [comment]
Hi @speigg, @HexaField 
Can you please update the description? ^^
Thanks.

**Comment by speigg** [comment]
At one point, gamepad button input (e.g. oculus controller buttons) was broken. I can't remember exactly what the issue was, but it may be fixed now. So, I suppose we can close this issue :)

**Comment by HexaField** [comment]
https://github.com/XRFoundation/XREngine/tree/dev/packages/engine/src/input/systems/ClientInputSystem.ts

handleGamepads is the function that processes gamepad API input into our input system, it is currently disabled as it has not been working for a while. this is still an issue
