### ISSUE TITLE
Begin revamp of documentation

### ISSUE THREAD

**Issue by shawwwwwwww** [XRFoundation/XREngine#3641]
We use this for documentation in our codebase: https://github.com/microsoft/tsdoc
We use this to turn that into documentation outside of the codebase: https://github.com/TypeStrong/typedoc 
We use this for showing our documentation on the web: https://docusaurus.io/
We automatically add the typedoc to Docusaurus with this: https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/docusaurus-plugin-typedoc
So you write documentation in your codebase and you get documentation on your site automatically

The problem is that there are many conflicts and errors causing docs not to build. Some of these are because we are not using re-exports (import {default as Foo} instead of import *) in some cases, or because things are duplicated and exported twice, or other problems like that

**Comment by HexaField** [comment]
we can't really do named imports as that's how reality packs know what to import. we will have to find another solution for this.
