### ISSUE TITLE
Fog Prefab

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#3660]
PR to be reviewed by @dinomut1 - David, please message him when this branch is ready for review.

**Fog** - total 8 story points

- [x] move fog from scene component to dedicated prefab & update existing default scenes - 2
- [x] add height based fog shader - 2
- [x] add brownian motion fog shader - 4

**Resources**

Height fog
  - https://discourse.threejs.org/t/possible-to-create-fog-with-vertical-dropoff/15015
  - https://woodenraft.games/blog/height-fog-implementation-three-js 
Brownian motion fog volume
  - https://youtu.be/k1zGz55EqfU
SDF based volumetric fog
  - https://blog.uhawkvr.com/rendering/rendering-volumetric-clouds-using-signed-distance-fields/

**Comment by dinomut1** [comment]
fog prefab implements all of this
