### ISSUE TITLE
When I click on a person, show context menu

### ISSUE THREAD

**Issue by shawwwwwwww** [XRFoundation/XREngine#3765]
![image](https://user-images.githubusercontent.com/18633264/137861411-d326d3d5-c327-45fd-8d84-283b2411bd3e.png)

![image](https://user-images.githubusercontent.com/18633264/137861438-2d819a72-ec2f-4534-9965-f3df36995ff3.png)

**Comment by kinjalravel** [comment]
@shawwwwwwww @HexaField @speigg  I am having some difficulty in identifying right click on Character by using three js

It would be really helpful if someone with three js experience can help me out with that  (Once it's started working then I will finish rest of the task )

**Comment by HexaField** [comment]
We want this to be made using etherealjs such that it is usable in VR. This context menu will allow further menus to be accessed, of which the details can be found here: https://github.com/XRFoundation/XREngine/issues/3127 https://github.com/XRFoundation/XREngine/issues/4430
