### ISSUE TITLE
XR UI Detail Effects

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#3943]
- [ ] Visual effects & sounds when passing over buttons
- [ ] Interaction Ray & Hit Cursor

**Comment by speigg** [comment]
Some inspiration:

![image](https://user-images.githubusercontent.com/507127/140544396-e269d347-be48-4457-8e7a-2ae866f34dbe.png)
![image](https://user-images.githubusercontent.com/507127/140544006-a1fb26d0-741c-411b-9a26-1de14a8983bf.png)
![image](https://user-images.githubusercontent.com/507127/140544028-e54cb9ec-f30a-4954-830f-372ae4dfe366.png)
