### ISSUE TITLE
Hookstate Bugs

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#3954]
There is one final set of bugs with the hookstate refactor.

All React side-effects and receptors need to be looked over

1) Any dependency lists need to be using `state.value` rather than `state`, and if any services are used inside these side-effects, their dependencies also need to be included expliclty in the deps array
2) We need to make sure we are not removing information that needs to stay (by using `set` or a `merge` with nested props that aren't receiving original state) 
2) We are creating garbage with each receptor call by creating `result` and `newValues` objects, these should be scope to individual cases to reduce garbage and removed where strictly unnecessary.
3) We also have redundant state, where some user auth state variables are in multiple state. (isLoggedIn,  isProcessing, error, authUser ....)

Examples: https://github.com/XRFoundation/XREngine/commit/f2e4bb7cd9e6dcaac0bcb5071af2d27113b9e736 https://github.com/XRFoundation/XREngine/commit/16d653fd16215490be57964de4d1847ab96d518e

**Comment by zulqarnainhanif** [comment]
@HexaField  Added fixes to [PR#3957](https://github.com/XRFoundation/XREngine/pull/3957)
