### ISSUE TITLE
Support .gltf file upload with resource files in the editor

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#3976]
Much like how other multi file resources are uploaded, we want to be able to drag and upload a gltf with associated resource files together into the editor 

Use this unzipped contents of this file for test purpose.
[glTF-instancing.zip](https://github.com/XRFoundation/XREngine/files/7910842/glTF-instancing.zip)

**Comment by NPatel10** [comment]
Use this file for test purpose.
[glTF-instancing.zip](https://github.com/XRFoundation/XREngine/files/7910842/glTF-instancing.zip)
