### ISSUE TITLE
Editor & Scene Serialization/Deseralization Overhaul

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#4086]
In an effort to integrate the editor more intimiately with the engine, usage of the ECS in an isomorphic fasion with runtime structures seems an elegant solution. Proposed here is a potential solution. Requirements identitied are as follows: 

- replace nodes & object mixin with functions that operate on components themselves. Nodes then simply become a template in the form of a pipe that applies necessary components to an entity

- unify the loading & saving functionality of the editor and locations. This is achieved by replacing the editor deserializer with the current location scene loading functionality (found in [SceneLoading.ts](https://github.com/XRFoundation/XREngine/tree/dev/packages/engine/src/scene/functions/SceneLoading.ts))

- gizmos & serialize (saving) functionality into their own functions

- a composable solution to remove existing replicated code

```ts
//  Engine package

const deserializeTransform = (entity: Entity, values: TransformType) => {
  const transformComponent = addComponent(entity, TransformComponent, { 
    position: new Vector3(),
    rotation: new Quaternion(),
    scale: new Vector3(1, 1, 1),
  })
  updateTransform(transformComponent, values)
  if(Engine.isEditor) addTransformGizmos(entity) // function redacted for brevity
}

const serializeTransform = (entity: Entity): TransformType => {
  const transform = getComponent(entity, TransformComponent)
  return {
    position: transform.position,
    rotation: transform.rotation,
    scale: transform.scale
  }
}

const updateTransform = (component: ComponentType<typeof TransformComponent>, values: Partial<TransformType>) => {
  values.position && component.position.copy(values.position)
  values.rotation && component.rotation.setFromEuler(
    new Euler().setFromVector3(new Vector3(values.rotation.x, values.rotation.y, values.rotation.z), 'XYZ')
  )
  values.scale && component.scale.copy(values.scale)
}

//  Editor package

type UpdateFunction = (component: ComponentType<any>, values: any) => void

const updateComponentPropertiesWithHistory = (updateFunc: UpdateFunction, component: ComponentType<any>, values: any) => {
  storeHistoryOnSelection(updateFunc, component, values) // function redacted for brevity
  updateFunc(component, values)
}

const TransformComponentEditor = ({ entity }) => {
  const transformComponent = getComponent(entity, TransformComponent)
  return (
    <Vector3Input
      value={transformComponent.position}
      onChange={(value) => updateComponentPropertiesWithHistory(updateTransform, transformComponent, { position: value })}
    />
    // extraneous code redacted for brevity
  )
}
```

cc @NPatel10 @speigg @NateTheGreatt @shawwwwwwww

**Comment by speigg** [comment]
Looks like a great approach to me. I love the direction this is going in. 

Btw, we should cleanup the allocations in `updateTransform`.

**Comment by NPatel10** [comment]
@speigg, I will keep in mind while working on this.
