### ISSUE TITLE
[Editor] Viewport panel covers editor working area

### ISSUE THREAD

**Issue by patreeceeo** [XRFoundation/XREngine#4110]
![image](https://user-images.githubusercontent.com/578371/141881590-bab85601-a40e-41e4-a484-52ae329e138d.png)

**Comment by zulqarnainhanif** [comment]
@HexaField which side do you want me to move viewport section to left or right?

**Comment by HexaField** [comment]
@zulqarnainhanif 

The view port is supposed to be hidden always, it is a limitation with rc-dock. If the dock context is unloaded and re-rendered the id of the dock changes, and the style is hardcoded to the id number. See EditorContainer.ts L#88
