### ISSUE TITLE
Embed youtube live streams through iframe

### ISSUE THREAD

**Issue by rtalwar26** [XRFoundation/XREngine#4140]
Live streams on youtube(and may be twitch ) can be embedded through iframe, which can bypass the CORS restriction.

An example how it is done in threejs playground is https://codepen.io/orvilleChomer/pen/mYBJzE

**Comment by HexaField** [comment]
The CSS3DRenderer is not very sophisticated, it has vast limitations with depth problems as it is not actually part of the same 3d scene the rest of the geometry is in. Here is an issue tracking twitch streams - the solution would be similar for youtube or any other video iframe embeds https://github.com/XRFoundation/XREngine/issues/2401
