### ISSUE TITLE
Add [USER ID] on login page

### ISSUE THREAD

**Issue by apolancojr** [XRFoundation/XREngine#4201]
Add the [USER ID] to https://localhost:3000/login to assist with the Admin System step described in the wiki here: https://github.com/XRFoundation/XREngine/blob/dev/tutorial/01-installation.md#admin-system

For reference, here is the documentation for finding one's userId:

in chrome dev tool write userId. This will display your user id (As shown in attached screenshot). Copy this user Id as string run it as following command in shell:

`npm run make-user-admin -- --id={COPIED_USER_ID}`

Example:
`npm run make-user-admin -- --id=c06b0210-453e-11ec-afc3-c57a57eeb1ac`

![image](https://user-images.githubusercontent.com/43248658/142813912-35f450e1-f012-4bdf-adfa-f0fa2816160f.png)
#4206

**Comment by barankyle** [comment]
Since userId's are rather long, this could probably be hidden by default and shown when clicking an icon that has a tooltip that says "Show User ID", or something like that.
