### ISSUE TITLE
[editor] Project list page doesn't show all projects?

### ISSUE THREAD

**Issue by patreeceeo** [XRFoundation/XREngine#4211]
Not sure how it got in this state, I just did a dev-reinit-db, then loaded the editor project list page which only showed the default project. I then tried to create a project named "Mappa" which resulted in an error modal saying that a project called "Mappa" already exists. I did have a Mappa project prior to dev-init-db, so perhaps something persisted from before the reinit?

PS I was sure to exit the server before running dev-reinit-db

**Comment by patreeceeo** [comment]
Also, the mappa project is installed and contains a .scene.json file. I thought that was supposed to lead to the creation of an associated project containing that scene? At any rate, I guess that's what's being persisted.

**Comment by HexaField** [comment]
This is intentional. For local development, projects will not be removed when running dev-reinit. Please see details here: https://github.com/XRFoundation/XREngine/blob/dev/tutorial/03-projects-api.md

**Comment by patreeceeo** [comment]
Still, it’s confusing. Why doesn’t it show in the UI?

**Comment by HexaField** [comment]
It should, if it doesn't that is a bug. You do need to restart the client & servers when you reinitialise, as the server will seed the database with the installed projects when it first starts up.

**Comment by patreeceeo** [comment]
Ok it's showing now after redoing the dev-reinit-db. Maybe it was user error.
