### ISSUE TITLE
[editor] pressing ENTER while focused on input doesn't submit in new project modal

### ISSUE THREAD

**Issue by patreeceeo** [XRFoundation/XREngine#4213]
STR:

Go to /editor
click create project button
type in a name
press ENTER

Usually pressing ENTER when focused on an input in a form submits the form.

Using Chromium 96 on Ubuntu 20.04

**Comment by zulqarnainhanif** [comment]
with material UI you need to press tab to switch focus from input field to button and then enter will work perfectly fine.

**Comment by patreeceeo** [comment]
Yes, that works. This issue is specifically about pressing ENTER while focused on the input. In the default HTML behavior, that submits the form, so I assume we'd want to follow that. It may just be a matter of adding a submit event handler to the surrounding form element. Anyway, this is based on my assumption of what's considered good UX. It would be surprising to me if we explicitly didn't want to do this, but then again I'm not a UX expert.

**Comment by HexaField** [comment]
@zulqarnainhanif would be great to follow up on this, adding a listener for 'enter' as patrick explains

**Comment by zulqarnainhanif** [comment]
sure @HexaField  i will implement a custom solution for this today and send a PR your way.
