### ISSUE TITLE
TSError: Property 'channel' does not exist on type 'Application'.

### ISSUE THREAD

**Issue by rtalwar26** [XRFoundation/XREngine#4229]
## on running

```shell
npm run dev-reinit
```

## getting following error

```shell
src/channels.ts:5:18 - error TS2339: Property 'channel' does not exist on type 'Application'.
```

**Comment by HexaField** [comment]
If on windows you likely need to run `npm run dev-reinit-db-windows` from server package. I have added `npm run dev-reinit-windows` which runs this package in root now too.

https://github.com/XRFoundation/XREngine/commit/462b4796e5e2c96aba582f90e8ae5fa577400f5e
