### ISSUE TITLE
Improve Typing Uniformity and Fix Errors

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#4239]
- All packages of the repo must adopt the tsconfig of the engine package, as it has quite specific and semi-strict types.
- All packages of the repo must have the check-errors npm script run "tsc --noemit" to ensure no errors
- [x] analytics
- [x] client 
- [x] client-core
- [x] common
- [x] editor
- [x] engine
- [x] gameserver
- [x] matchmaking
- [x] ops
- [x] projects
- [x] server
- [x] server-core

**Comment by zulqarnainhanif** [comment]
working on the analytics and client workspace to improve import ordering and removing type errors showing up in VS Code.

**Comment by zulqarnainhanif** [comment]
Moving on to client-core workspace next.
