### ISSUE TITLE
Hookstate Global Scope Refactor - RFC

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#4310]
XREngine relies quite heavily on global state via top level hookstate stores, which causes problems partciularly with tests.

- must enable receptor registration in expected order - achieved by moving from global scope to component mount useEffect
- create store object, when created store at client app load `store.instance = createStore() { ... }`

```ts
// store.ts

export const store = { instance: null! }

export const createStore = () => { 
  store.instance = { ... }
}

// AuthService.ts

type AuthStateProps = {
  //... auth state types
}

type AuthStateType = State<AuthStateProps> & StateMethodsDestroy

const state = { instance: null! as StateType }

export function createAuthServiceState(store, force: boolean) {
  if(store.instance && !force) return // force function used for testing
  const newState = createState({ ... } as StateType)
  state.instance = newState
  store.register(newState)
}

export const useAuthState = useState(state.instance) as StateType

// example.ts

const ExampleComponent = () => {
  const authState = useAuthState()
  useEffect(() => {
    createAuthServiceState(store)
  }, [])
}
```

**Comment by speigg** [comment]
All of this is cleaner if we don't register state in the same place that we define it; in other words, we should import state creation functions and register everything in the store in the same place, much like we do with systems (we can rely on `import.meta.glob` now that this won't cause issues in our toolchain).

**Comment by speigg** [comment]
```ts 
// AuthService.ts
export function createState() {
  return createState({ ... })
}

// Store.ts
createStore(serviceModules:{key:string, createService:()=>{state:any, receptor:(state)=>void}[]}) {
  return Object.fromEntries(serviceModules.map(service => [service.key, service.createService()]))
} 

// Engine.ts, init function
Engine.store = createStore() 
```

**Comment by HexaField** [comment]
> All of this is cleaner if we don't register state in the same place that we define it; in other words, we should import state creation functions and register everything in the store in the same place, much like we do with systems (we can rely on `import.meta.glob` now that this won't cause issues in our toolchain). 

The issue here is this is not extendible. Every service would have to be declared in client-core and registered for every route. For example, any services defined in the editor package or the project package would have to be imported from client-core, thus breaking the monorepo hierarchy and the point of projects altogether.

How can this be done the other way around (as in the original post in this thread)?

**Comment by speigg** [comment]
Another variation: 

```ts
// store.ts

interface Service {
  state: State<any>,
  receptor: () => void
}

export const Store = { instance: null! as Map<string, Service> }

export const accessService = (initializer:() => Service) => { 
  if (!Store.instance) throw new Error('Store is not initialized')
  if (Store.instance.has(key)) return Store.instance.get(key)
  const service = initializer()
  Store.instance.add(key, service)
  return service
}

// AuthService.ts

export function createAuthService() {
  return {state: createState({ ... }), receptor: authReceptor}
}

export function authReceptor() { ... }

export function accessAuthState() {
  return accessService(createAuthService).state
}

// example.ts

const ExampleComponent = () => {
  const userState = useState(accessAuthState().user)
}```

**Comment by HexaField** [comment]
closing in favour of Hyperflux
