### ISSUE TITLE
Include all editor nodes in a single test scene

### ISSUE THREAD

**Issue by speigg** [XRFoundation/XREngine#4327]
We should include all of our editor nodes in a single `test.scene.json` in the default project, for integration and e2e tests. 

- [ ] AmbientLightNode in unified test scene
- [ ] AudioNode in unified test scene
- [ ] BoxColliderNode in unified test scene
- [ ] CameraPropertiesNode in unified test scene
- [ ] CloudsNode in unified test scene
- [ ] CubemapBakeNode in unified test scene
- [ ] DirectionalLightNode in unified test scene
- [ ] GroundPlaneNode in unified test scene
- [ ] GroupNode in unified test scene
- [ ] HemisphereLightNode in unified test scene
- [ ] ImageNode in unified test scene
- [ ] InteriorNode in unified test scene
- [ ] LinkNode in unified test scene
- [ ] MapNode in unified test scene
- [ ] MetadataNode in unified test scene
- [ ] ModelNode in unified test scene
- [ ] OceanNode in unified test scene
- [ ] ParticleEmitterNode in unified test scene
- [ ] PointLightNode in unified test scene
- [ ] PortalNode in unified test scene
- [ ] PostProcessingNode in unified test scene
- [ ] SceneNode in unified test scene
- [ ] ScenePreviewCameraNode in unified test scene
- [ ] SkyboxNode in unified test scene
- [ ] SpawnPointNode in unified test scene
- [ ] SplineHelperNode in unified test scene
- [ ] SplineNode in unified test scene
- [ ] SpotLightNode in unified test scene
- [ ] SystemNode in unified test scene
- [ ] TestModelNode in unified test scene
- [ ] TriggerVolumeNode in unified test scene
- [ ] VideoNode in unified test scene
- [ ] VolumetricNode in unified test scene
- [ ] WaterNode in unified test scene

**Comment by HexaField** [comment]
The sky-station should act as our test scene
