### ISSUE TITLE
CORS issue between different local ports

### ISSUE THREAD

**Issue by fynv** [XRFoundation/XREngine#4433]
Hi, I'm experiencing some issues during XREngine local installation.

After finishing all the steps in the [tutorial](https://github.com/XRFoundation/XREngine/blob/dev/tutorial/01-installation.md), using Ubuntu 20.04，now the client is serving at port 3000, which is correct.

However, when I try to access any of the pages, I get a blank page, and see  errors like:
![2021-12-10 17-38-43 的屏幕截图](https://user-images.githubusercontent.com/8346412/145553423-a59ee33e-9aab-434a-96a1-6e10c53c5899.png)

Looks like there's issue cross-accessing the 3030 port on the same host.

Any idea how to fix this?

**Comment by HexaField** [comment]
This usually isn't a CORS issue, but that there is some error in the API Server (running in port 3030). Check that there is no crash log and that you have correctly set up docker & agones.

**Comment by semateos** [comment]
I'm seeing the same thing after following the installation instructions. If I click to open one of those urls with the CORS complaint, they open fine. Nothing bad looking in the console log - just a bunch of health check pings from [agones] that look fine.

**Comment by fynv** [comment]
Turns out that I have to access using the address "https://localhost:3000/location/test" instead of "https://127.0.0.1:3000/location/test"

**Comment by HexaField** [comment]
Ah, yes, it does help to unify everything in .env.local to the same host name. I use my LAN IP such that I can access from other devices over LAN, and it solves this problem too.
