### ISSUE TITLE
eliminate redundant `getComponent` calls

### ISSUE THREAD

**Issue by NateTheGreatt** [XRFoundation/XREngine#4458]
currently in the codebase most functions that deal with components are retrieving access to them via `getComponent` in the beginning of the function definition:
```js
const someFunction = (entity) => {
  const someComponent = getComponent(entity, someComponent)
  someComponent.value /= 2
}

const someOtherFunction = (entity) => {
  const someComponent = getComponent(entity, someComponent)
  someComponent.value /= 4
}
```

however, most of these functions are being used in a context where the components have already been retrieved, or will need retrieved again in a following function, thus creating a lot of redundant `getComponent` calls:
```js
const someSystem = (world) => {
  const entities = query(world)
  for (const entity of entities) {
    const someComponent = getComponent(entity, someComponent)

    someComponent.value += 100
    
    someFunction(entity)
    
    someOtherFunction(entity)
  }
}
```

this can have a potentially significant impact on performance by inducing more lookups than are necessary.

in order to eliminate these redundant component retrievals, `getComponent` should be called once per entity iteration in a system, the reference of which can then be passed into the respective function calls.
```js

const someFunction = (someComponent) => {
  someComponent.value /= 2
}

const someOtherFunction = (someComponent) => {
  someComponent.value /= 4
}

const someSystem = (world) => {
  const entities = query(world)
  for (const entity of entities) {
    const someComponent = getComponent(entity, someComponent)

    someComponent.value += 100
    
    someFunction(someComponent)
    
    someOtherFunction(someComponent)
  }
}
```

in this example, it reduces the number of lookups by `3 * entities.length`. it also makes the functions more referentially transparent (see https://github.com/XRFoundation/XREngine/issues/4460)

**Comment by NateTheGreatt** [comment]
related https://github.com/XRFoundation/XREngine/issues/4460

**Comment by HexaField** [comment]
moving this to our style guide https://github.com/XRFoundation/XREngine/wiki/Style-Guide
