### ISSUE TITLE
enhance referential transparency

### ISSUE THREAD

**Issue by NateTheGreatt** [XRFoundation/XREngine#4460]
currently in the codebase most functions do not exhibit [referential transparency](https://medium.com/@olxc/referential-transparency-93352c2dd713)

referential transparency can considerably enhance the readability of code, making it easier to work with for coders well-versed in the codebase and _especially_ helps coders who are new to the codebase figure out what's going on.

**Comment by HexaField** [comment]
Moving this to our style guide https://github.com/XRFoundation/XREngine/wiki/Style-Guide
