### ISSUE TITLE
UI improvement /admin/routes

### ISSUE THREAD

**Issue by zulqarnainhanif** [XRFoundation/XREngine#4603]
The table view should take full height available rather than being scrollable

<img width="1680" alt="Screenshot 2021-12-30 at 10 10 16 PM" src="https://user-images.githubusercontent.com/30355034/147773489-3e84f380-17ec-4346-8532-d4e421327433.png">

**Comment by HexaField** [comment]
we could also reduce the height of the rows a bit to fit more in, and standardise this across all the tables
