### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by zulqarnainhanif** [XRFoundation/XREngine#4606]
The sidepanel submenus heading should have different text and icon then the elements within.

<img width="197" alt="Screenshot 2021-12-30 at 10 19 06 PM" src="https://user-images.githubusercontent.com/30355034/147774078-73725221-3b74-4a18-ba49-44f7332ce999.png">

**Comment by HexaField** [comment]
We can get rid of the nested menu items honestly, just make it all flat.
