### ISSUE TITLE
Admin/User Route needs improvement in admin panel

### ISSUE THREAD

**Issue by zulqarnainhanif** [XRFoundation/XREngine#4607]
- The search field doesn't work tried with name and avatar column. (image#2)
- The create user flow crashes the app. (image#3)
- The delete user confirmation popup should have `username` instead of saying `this user`. (image#4)
- The delete user functionality crashes app but deletes user successfully. (image#5)
- Click view in table column -> edit role -> change role -> submit. The role in the table doesn't get updated until a refresh.
- Need to improve spacing in the view button view of users. Too much space in user scopes, no space below buttons etc (image#6)

**image#2**
<img width="1290" alt="Screenshot 2021-12-30 at 10 25 02 PM" src="https://user-images.githubusercontent.com/30355034/147774412-dca46207-693d-434c-92c5-ffc3b0e601f1.png">

**image#3**
<img width="1676" alt="Screenshot 2021-12-30 at 10 27 24 PM" src="https://user-images.githubusercontent.com/30355034/147774561-73fad949-36b5-418d-b097-af9ff250987c.png">

**image#4**
<img width="1208" alt="Screenshot 2021-12-30 at 10 29 18 PM" src="https://user-images.githubusercontent.com/30355034/147774809-c6d9f424-8fd5-4825-9961-93333aebc866.png">

**image#5**
<img width="1676" alt="Screenshot 2021-12-30 at 10 31 14 PM" src="https://user-images.githubusercontent.com/30355034/147774833-a3e52e53-73bd-43ac-b0a0-5bedcb5d1a80.png">

**image#6**
<img width="544" alt="Screenshot 2021-12-30 at 10 35 39 PM" src="https://user-images.githubusercontent.com/30355034/147775228-9b513409-1b7b-4d0f-b989-c6c881daac87.png">

**Comment by zulqarnainhanif** [comment]
@HexaField The social tab are same as users or is there any difference if there is not difference can we remove them from sidepanel?

**Comment by HexaField** [comment]
> @HexaField The social tab are same as users or is there any difference if there is not difference can we remove them from sidepanel?

Social is from an old project, those three pages can be removed entirely
