### ISSUE TITLE
There is trouble establishing channel connection sometimes.

### ISSUE THREAD

**Issue by zulqarnainhanif** [XRFoundation/XREngine#4622]
since we are unable to establish channel connection the audio video button doesn't show up on center top

<img width="1680" alt="Screenshot 2022-01-01 at 2 41 22 AM" src="https://user-images.githubusercontent.com/30355034/147839544-fe4aee82-6544-4ad7-895c-27733f20f14e.png">

**Comment by HexaField** [comment]
@zulqarnainhanif I have pushed some improvements to this recently, could you please give this another test?

**Comment by zulqarnainhanif** [comment]
Today i keep on getting this screen and world disconnects and route refreshes after 30sec

<img width="1680" alt="Screenshot 2022-01-06 at 12 41 36 AM" src="https://user-images.githubusercontent.com/30355034/148278763-3c3267c9-b776-478d-98d5-f2f42b4b02d6.png">
