### ISSUE TITLE
Error on installing -  Error: write EPIPE

### ISSUE THREAD

**Issue by sjcotto** [XRFoundation/XREngine#4631]
Hi, I'm having issues installing following the steps on the tutorial

after running

`npm run dev`

it shows the following error: 

`[client] (this will be run only when your dependencies or config have changed)
[client] node:events:368
[client]       throw er; // Unhandled 'error' event
[client]       ^
[client] 
[client] Error: write EPIPE
[client]     at afterWriteDispatched (node:internal/stream_base_commons:164:15)
[client]     at writeGeneric (node:internal/stream_base_commons:155:3)
[client]     at Socket._writeGeneric (node:net:795:11)
[client]     at Socket._write (node:net:807:8)
[client]     at writeOrBuffer (node:internal/streams/writable:389:12)
[client]     at _write (node:internal/streams/writable:330:10)
[client]     at Socket.Writable.write (node:internal/streams/writable:334:10)
[client]     at Object.writeToStdin (/root/XREngine/node_modules/vite/node_modules/esbuild/lib/main.js:1864:19)
[client]     at sendResponse (/root/XREngine/node_modules/vite/node_modules/esbuild/lib/main.js:642:14)
[client]     at handleRequest (/root/XREngine/node_modules/vite/node_modules/esbuild/lib/main.js:664:13)
[client] Emitted 'error' event on Socket instance at:
[client]     at emitErrorNT (node:internal/streams/destroy:157:8)
[client]     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[client]     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[client]   errno: -32,
[client]   code: 'EPIPE',
[client]   syscall: 'write'
[client] }
`

I think it's related to this Dockerfile https://github.com/XRFoundation/XREngine/blob/dev/dockerfiles/client/Dockerfile-client but i'm not sure why or what I can do to prevent it

**Comment by shawwwwwwww** [comment]
Hello,

Sorry it's taken a minute to catch this issue.

If you need more real-time help you can come to our Discord.

It vlooks front he log like it could be a Node.js version thing. if you run node --version, what are you on? We support 16+


We use Docker to run the database. To start the db and verify that's working:
```
cd scripts && sudo bash startdb.sh 
```

Everything else is running Node.js so it's mostly likely something on that side.

Ping me if you have other issues.
