### ISSUE TITLE
Let's build it together?

### ISSUE THREAD

**Issue by motifdev** [XRFoundation/XREngine#4698]
You say "Let's build it together" but your engine can't be installed and I will never build on anything like this.
I tried intel mac, mac m1,  mac docker, ubuntu 22, ubuntu 18, ubuntu docker. I got exact same error messages that you can find in issues and I asked myself why the f I should contribute to this.  Just close source it man, at least people won't lose time trying to  install it.

**Comment by shawwwwwwww** [comment]
Heya, sorry you're frustrated. It's a complex project -- basically when you start things up you're starting up the entire infrastructure. There are a few gotchas as a result of that complexity, and we're a relatively small team for the scale of the project. The purpose of open sourcing it is really that we hope others will come help us smooth out any issues.

That being said, happy to help you solve this, but need some info on how I can reproduce.

What were the steps that you took?

What errors did you run into?

Have you tried running the master branch? We've changed a lot, and it's possible there's just something in dev that is an issue, but there are maybe 50-60 engineers right now building projects on the latest version of engine across different OSes and such. I personally use ubuntu 20, but I've used 18 and WSL.

**Comment by HexaField** [comment]
Hey @motifdev , thanks for sharing your concern. I'm sorry you have trouble getting this thing set up, please feel free to join our discord where we can provide more synchronous support and step you through whatever troubles you're having. We have been building this thing off the sweat on our backs for almost 2 years, and while it is still rough around the edges, we are determined to keep it open and free for everyone to use.
