### ISSUE TITLE
error building standalone client

### ISSUE THREAD

**Issue by 1S33dp1sk** [XRFoundation/XREngine#4704]
using the `dev` branch
in `packages/client/src/server.js` is missing the  `vite.config.js` and running without it will throw an error. 
Nonetheless, using `npm run dev` will cause 

> [vite]` Failed to load source map for /src/hookstate_devtools.es.js`

**Comment by HexaField** [comment]
`packages/client/src/server.js` does not exist, but `packages/client/server.js` does, do you mean this file? either way, I am not sure what you mean by "missing the `vite.config.js`". can you please provide the error you see?

Regarding the hookstate devtools logging, this is considered normal behvaior.

**Comment by HexaField** [comment]
Closing after 14 days of inactivity. If you are still experiencing issues, please provide some more information or reach out on our discord. https://discord.gg/xrf
