### ISSUE TITLE
Rotation Property group is not working properly

### ISSUE THREAD

**Issue by NPatel10** [XRFoundation/XREngine#4733]
Rotation Properties in editor is not working properly when being set from the properties panel. When you open an editor and select any object then in Properties panel you can see transform properties like, Position, Rotation, Scale. Among these Rotation is not working properly. To recreate issue, set the X or Z values to non zero and then change the Y value of the property.

**Comment by HexaField** [comment]
While this does seem to be solved, it could still be improved. When I scrub the euler slider, after a few changes It jumps large values, after a few values only displaying the new value when I let go of the mouse.
