### ISSUE TITLE
getFileKeysRecursive will attempt to download similarly-named folders

### ISSUE THREAD

**Issue by barankyle** [XRFoundation/XREngine#4827]
I was trying to save a backup of an old version of the msa project files in S3 in case the new version had issues. I'd made a copy of 'projects/msa' in S3 to a directory in the same bucket named 'projects/msa-backup-1-18-22' . When downloadProjects ran,the call to getFileKeysRecursive found matches on both folders, and first tried to download from 'projects/msa-backup-1-18-22', and then promptly failed with 

```
[ProjectLoader]: - downloading "projects/msa-backup-1-18-2022/"
[ProjectLoader]: WARNING file "projects/msa-backup-1-18-2022/" is empty
[ProjectLoader]: Failed to download project with error Error: EISDIR: illegal operation on a directory, open '/app/packages/projects/projects/msa-backup-1-18-2022/'
```

I think downloadProjects.ts needs to pass `projects/${projectName}/` into getFileKeysRecursive (note the trailing slash), so that it only fetches from a projects directory that exactly matches that name.

**Comment by HexaField** [comment]
Good catch
