### ISSUE TITLE
Avatar gets stuck in /location/apartment

### ISSUE THREAD

**Issue by zulqarnainhanif** [XRFoundation/XREngine#4865]
The character gets stuck in the wall of corridor behind him from where he is spawned and many other walls that encloses the apartment.

<img width="1301" alt="Screenshot 2022-01-21 at 1 56 49 AM" src="https://user-images.githubusercontent.com/30355034/150420952-bf72b554-c221-40bd-91f5-bde17ed9d254.png">

**Comment by HexaField** [comment]
Foudn the problem here. The box colliders have a negative dimension, which it seems the physics engine is interpreting just fine but causing problems. Will solve this by putting Math.abs() on scene deserialziers as well as fixing the scene.
