### ISSUE TITLE
scene loading is crashes on trying to import projects custom systems

### ISSUE THREAD

**Issue by XiaNi** [XRFoundation/XREngine#4996]
sometime scene loading is crashes on trying to import projects custom systems
![image](https://user-images.githubusercontent.com/273573/151798290-13095418-593d-434b-beae-91b3a27f418d.png)

**Comment by HexaField** [comment]
Looks like you have `///` in the URL as well, this is likely due to an incorrect entry in the database for the project name, im not sure how you managed that.

**Comment by XiaNi** [comment]
@HexaField 
problem was that sometimes locationState.currentLocation.location.sceneId.value was not loaded yet (while     projectState.projects.value was, and engineState.isEngineInitialized is set to true).
and this part was unable to extract "project"
`const [project] = locationState.currentLocation.location.sceneId.value.split('/')`
and then 
`const filePathRelative = new URL(filePath).pathname.replace(`/projects/${project}/`, '')`
was failing to remove `/projects/msa/` in `/projects/msa/tournament/logic/TournamentSystem.ts` cause it was searching for `/projects//`
so filePathRelative stays full `/projects/msa/tournament/logic/TournamentSystem.ts`
and then when we do
```import(`./projects/${project}/${entryPointSplit}.ts`)```
it resolves to
`import('./projects///projects/msa/tournament/logic/TournamentSystem.ts')`
(import(`./projects/<empty>/<fullPathname>`))

my fix was to add locationState.currentLocation.location.sceneId.value to useEffect dependencies array and then check that it's not empty.
