### ISSUE TITLE
/location/test keep refreshing as /location/undefined

### ISSUE THREAD

**Issue by zulqarnainhanif** [XRFoundation/XREngine#5217]
The app keeps on getting redirected to /location/undefined as soon as i come close to the box below in image

<img width="2050" alt="Screenshot 2022-02-16 at 12 47 04 AM" src="https://user-images.githubusercontent.com/30355034/154138841-173e0b9e-5a0a-4173-8277-f6bb0f0b94b5.png">

**Comment by HexaField** [comment]
You might be entering a portal, can you check the editor to see if there is a node there in the editor?

**Comment by zulqarnainhanif** [comment]
Yes there is a portal there in the editor @HexaField

**Comment by HexaField** [comment]
Cool, i'll add the frame model so it's more obvious.
