### ISSUE TITLE
Fix ReadyPlayerMe login

### ISSUE THREAD

**Issue by barankyle** [XRFoundation/XREngine#5233]
The ReadyPlayerMe login does not appear on the /login page, and nothing loads when the "Log in with ReadyPlayerMe" button is clicked when at a location.

**Comment by HexaField** [comment]
this will be fixed in https://github.com/XRFoundation/XREngine/pull/5168

**Comment by HexaField** [comment]
Just tested on that branch, the readyplayerme login does not appear on /login
