### ISSUE TITLE
Configure OAuth for QAT cluster

### ISSUE THREAD

**Issue by hanzlamateen** [XRFoundation/XREngine#5252]
Currently OAuth based authentication is not working for QAT.

**Comment by barankyle** [comment]
@hanzlamateen I've added https://api-qat.theoverlay.io as a callback to all of the apps. Let me know if any of them are still not working on QAT.

**Comment by hanzlamateen** [comment]
> 

Shouldnt it be `https://qat.theoverlay.io` instead of api-qat?

**Comment by barankyle** [comment]
No, OAuth's negotiation happens between the service and the API server. The callback URL that you register with an OAuth app is the API server that it will return to after the negotiation is complete.

**Comment by barankyle** [comment]
All OAuth providers are now working on QAT.
