### ISSUE TITLE
Fine grain customisation  & scope based permission

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#5265]
We can make user-permissions scope match the jsonschema too.

We can define some default users w/ scopes. Such as:

SuperAdmin - edit ANYTHING

OrgAdmin - be the host of something - create/edit ALL org/worlds/users on org domains

OrgMember - be a host employee  - create/edit SOME org/worlds/users on org domains

OrgUser - have org permissions - create/edit SOME org/worlds on org domains

Guest - visit public links/invites given

Global create & edit scopes
example:
- org:edit

Id based create & edit scopes
- org:edit:[id]

for the following:
- [ ] org
- [ ] world
- [ ] scene
- [ ] location
- [ ] users
- [ ] invites
- [ ] files

**Comment by HexaField** [comment]
https://github.com/XRFoundation/XREngine/issues/4715

**Comment by HexaField** [comment]
- [ ] replace 'admin' userRole with admin scope
- [ ] replace explicit 'guest' & 'user' with implicit identity-provider query call

**Comment by barankyle** [comment]
When pulling a GH project repo, private repos should have all files be private in S3 other than the assets folder. Public GH repos should be all public in S3.

**Comment by barankyle** [comment]
Files currently in /projects need to be moved to each folder in projects/{project_name}/

Current projects/projects will be projecs/{project_name}/projects.

(rollup dynamic import package only supports one level deep of variables in path)

**Comment by barankyle** [comment]
Possibly have something in the authentication that adds the user's organization to API requests, skips it for calls that don't matter (or if the user is a superAdmin).

**Comment by barankyle** [comment]
Need a default org for each deployment, and each org needs to have the default project.

**Comment by barankyle** [comment]
Scope table needs to have a new column 'organization'. Combined with auth logic to add user's org to requests, this should handle a lot of the authentication of operations.

**Comment by barankyle** [comment]
Orgs need an admin page for deleting the org and changing the name. Can't change the domain, if you want a different domain you'll have to make a new org and migrate everything over.

**Comment by barankyle** [comment]
Orgs seem to need separate builder + deployment so that docker images aren't commingling organizations and so that images don't get huge. Will need some identification on pods to mark them as belonging to an org so that they can only be accessed by that org.
