### ISSUE TITLE
Physics Engine Bugs

### ISSUE THREAD

**Issue by hamzzam** [XRFoundation/XREngine#5275]
Will populate the list as new issues are came across. Adding the currently known below:

1.  Adding mass to the physics body leads to the collider going inside the ground.
2. Grouping of models (with physics attribute set) in the editor, leads to the inaccurate position of colliders on scene load. (Maybe world position should be used? but that might not work for nested cases.)

**Comment by hamzzam** [comment]
Physics mesh scale is not always scaled properly. Mainly when one of the children mesh of the object do not have the default scale. And the physics object is just using the root scale.

**Comment by hamzzam** [comment]
Collider debug mesh's scale is not updated in real-time in the editor. Editor needs to be reloaded to see the new mesh bounds.

**Comment by hamzzam** [comment]
Avatar collider is at a buggy position.

![image](https://user-images.githubusercontent.com/15801128/171969636-db44a268-668b-4234-b934-422e04df6cd5.png)

**Comment by HexaField** [comment]
Closing in favour of https://github.com/XRFoundation/XREngine/issues/4296
