### ISSUE TITLE
AR for eCommerce component

### ISSUE THREAD

**Issue by Griffisaurus** [XRFoundation/XREngine#5295]
https://modelviewer.dev/

bring the feature back from the long long ago https://github.com/XRFoundation/XREngine/commit/7f2cb3a9e3ba7355efc134fbc945aba080a414c1

Look around for old code that was removed.
https://github.com/XRFoundation/XREngine/search?q=model-viewer

**Comment by mrhegemon** [comment]
I'm down for whatever, but a quick webxr/quick-look shim for model viewing would be HUGE investor ROI for an engineering task 

Cool thing about model viewer is that it can work on ios out of the box w/
https://developer.apple.com/augmented-reality/quick-look/

<model-viewer camera-controls alt="A 3D model of an astronaut" ar ios-src="../../shared-assets/models/Astronaut.usdz">
</model-viewer> 

an old concept shot
![The Overlay Partner_Investor Deck](https://user-images.githubusercontent.com/5104160/155253971-90ef2cac-5e94-4249-ba01-dada60299707.png)
