### ISSUE TITLE
[Editor] Toggle Physics Helper Button not showing correct state for the first time

### ISSUE THREAD

**Issue by zulqarnainhanif** [XRFoundation/XREngine#5376]
when a scene is loaded for the first time the editor is showing physics helpers but the button shows disabled state. After toggling once or changing scene it starts working fine.

<img width="38" alt="Screenshot 2022-03-02 at 2 10 14 PM" src="https://user-images.githubusercontent.com/30355034/156331023-2094b2c7-15e9-43ae-99c5-aad11a6dee3a.png">
<img width="1532" alt="Screenshot 2022-03-02 at 2 10 26 PM" src="https://user-images.githubusercontent.com/30355034/156331030-cd9962ca-0838-489d-8c9d-cd947a5f56d8.png">

**Comment by NPatel10** [comment]
This issue is resolved
