### ISSUE TITLE
Standardise Colors

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#5398]
our color scheme should use the colors the homepage does
https://app.theoverlay.io/

Standardize Colors

background-color: #5f5ff1;
background: rgba(31,27,72,.85);
background: linear-gradient(92.22deg,#5236ff,#c20560); (edited)

- [x] admin panel
- [x] locations
- [x] editor

**Comment by mrhegemon** [comment]
![image](https://user-images.githubusercontent.com/5104160/156868534-db62d232-fed6-49ef-a963-0762aa9de9a5.png)

**Comment by mrhegemon** [comment]
![unknown](https://user-images.githubusercontent.com/5104160/158686067-a7d82f98-3f41-4d74-a447-e1432ffb7a45.png)

Expanded color set - open to better ideas
https://paletton.com/#uid=73+1c0kmOV83x+Nf7YjtOOnzHr3

**Comment by zulqarnainhanif** [comment]
using
https://paletton.com/#uid=13+1c0kmOV8gYUOjZUOpEVFqgJY
