### ISSUE TITLE
Portals send users other than the one who entered them to the linked location

### ISSUE THREAD

**Issue by barankyle** [XRFoundation/XREngine#5460]
When testing the shopping scene/location, one user entering the globe-theater portal triggered both users redirecting to it, even when the other user was some distance away from the portal (on one of the ramps near the spawn point)

**Comment by HexaField** [comment]
This is almost definitely to do with how we are processing the events on each client, we likely just need an if statement somewhere detecting if the local client entity is in fact the one who collided with the portal
