### ISSUE TITLE
Add Help details of controller binding. On windows also show high performance tweaks - in settings menu?

### ISSUE THREAD

**Issue by mrhegemon** [XRFoundation/XREngine#5479]
https://www.figma.com/file/QfnVv6akpN1Ccx83MZHWXN/EE-Keyboard-Tutorial?node-id=202%3A2

Add tutorial screens for:

On desktop
Keyboard / Mouse

On Mobile
Touch

All times:
Show XR Controllers
Show Controller

On windows show this:

So, looks like much of the time chrome runs on the discrete GPU
Saw a huge performance consequence w/ @GriffinRowell's computer
https://support.google.com/chrome/thread/77636044/chrome-to-use-specific-gpu

configure Chrome to use the Nvidia graphics card.

Below are the steps applied:
Nvidia Driver Version
Upon checking on the Nvidia graphic card driver version, it was long outdated. Hence I run the DDU (Display Driver Uninstaller) for clean uninstallation and re-install with the latest driver from Nvidia site.

Nvidia Control Panel
The Nvidia control panel was also re-installed. With the Chrome program pointing to "High performance".

Nvidia control panel pointing to Chrome.
![image](https://user-images.githubusercontent.com/5104160/158228629-cb81c441-b975-407f-93d9-af4cea464d41.png)

Graphics Performance Preference
Under Windows graphics preference, Chrome was also configured to "High performance".

Lastly, besides applying the above steps , it just wouldn't work. I had to sign out from the windows account and re-login. If that doesn't work, can give the PC a try of restarting as well.

 also, Nvidia control panel pointing to Chrome.
![image](https://user-images.githubusercontent.com/5104160/158228629-cb81c441-b975-407f-93d9-af4cea464d41.png)

in settings for windows 10/11, search 'Graphics' preference on AMD/Nvidia for Chrome application.
![image](https://user-images.githubusercontent.com/5104160/158228864-3e9c1423-12db-49c9-acbb-e2a381ba3b9e.png)

**Comment by johnfelipe** [comment]
that option is not currently with latest control settings, this one is latest:

![SNAG-1151](https://user-images.githubusercontent.com/428820/171629549-c237f0c8-25cb-4721-b82a-d513b4f7093f.png)

in this latest version wich one select?

**Comment by mrhegemon** [comment]
<img width="630" alt="Screen Shot 2022-08-08 at 11 53 55 AM" src="https://user-images.githubusercontent.com/5104160/183493401-853c73ca-511d-4065-b882-2f1284280624.png">
