### ISSUE TITLE
[Editor] UI improvement

### ISSUE THREAD

**Issue by zulqarnainhanif** [XRFoundation/XREngine#5505]
The popup opened on right clicking any node in hierarchy gets behind the Element list container if opened around the edge near it as shown in image below:

<img width="381" alt="Screenshot 2022-03-17 at 1 11 03 AM" src="https://user-images.githubusercontent.com/30355034/158682067-0e2ccee2-a4d7-474a-b6d4-4f1e955a48e4.png">

**Comment by NPatel10** [comment]
This issue is resolved.
