### ISSUE TITLE
Avatar ground detection needs tweaking

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#5508]
The falling animation is too sensitive, it plays when going down slopes and when walking on obstacles. The puttclub scene has a lots of similar issues where the animations dont really work properly. my theory is it is to do with not using raycasting to detect proximity to the ground properly.

**Comment by mohsenheydari** [comment]
The ray-ground intersection test is not very stable, in turn, it causes the `AvatarComponent.isGrounded` value to be unstable. Previously, the animation system used this value to trigger jumping animations.
