### ISSUE TITLE
[Ticket]: I have: Build the image - RUN npm run build-client - Unexpected token.

### ISSUE THREAD

**Issue by root-deeptown** [XRFoundation/XREngine#5520]
[close] - No problem at XREngine --depth branch.

Have a nice day. 
I can not build the image. (master branch)

...
=> CACHED [21/23] COPY . .                                                                                                                                                         0.0s
 => [22/23] RUN npm run check-db-exists                                                                                                                                            43.1s
 **=> ERROR [23/23] RUN npm run build-client**                                                                                                                                         63.4s 
                                                                                                                                                                             
 > [23/23] RUN npm run build-client:                                                                                                                                                     
#27 1.239                                                                                                                                                                                
#27 1.239 > xrengine@0.2.5 build-client                                                                                                                                                  
#27 1.239 > cd packages/client && npm run build                                                                                                                                          
#27 1.239                                                                                                                                                                                
#27 1.633 
#27 1.633 > @xrengine/client@0.5.1 build
#27 1.633 > cross-env NODE_OPTIONS=--max_old_space_size=10240 vite build
#27 1.633 
#27 4.478 vite v2.8.1 building for production...
#27 4.602 transforming...
#27 40.52 transforming...
#27 46.25 ✓ 4 modules transformed.
#27 48.19 rendering chunks...
#27 62.19 ✓ 13245 modules transformed.
**#27 62.19 [rollup-plugin-dynamic-import-variables] Unexpected token (33:26**)
#27 62.19 file: /app/packages/server-core/src/appconfig.ts:33:26
#27 62.19 error during build:
**#27 62.19 SyntaxError: Unexpected token (33:26)**
#27 62.19     at Parser.pp$4.raise (/app/node_modules/rollup/dist/shared/rollup.js:19636:13)
#27 62.19     at Parser.pp$9.unexpected (/app/node_modules/rollup/dist/shared/rollup.js:16932:8)
#27 62.19     at Parser.pp$9.semicolon (/app/node_modules/rollup/dist/shared/rollup.js:16909:66)
#27 62.19     at Parser.pp$8.parseExpressionStatement (/app/node_modules/rollup/dist/shared/rollup.js:17392:8)
#27 62.19     at Parser.pp$8.parseStatement (/app/node_modules/rollup/dist/shared/rollup.js:17125:24)
#27 62.19     at Parser.pp$8.parseBlock (/app/node_modules/rollup/dist/shared/rollup.js:17408:21)
#27 62.19     at Parser.pp$8.parseStatement (/app/node_modules/rollup/dist/shared/rollup.js:17090:36)
#27 62.19     at Parser.pp$8.parseBlock (/app/node_modules/rollup/dist/shared/rollup.js:17408:21)
#27 62.19     at Parser.pp$8.parseStatement (/app/node_modules/rollup/dist/shared/rollup.js:17090:36)
#27 62.19     at Parser.pp$8.parseIfStatement (/app/node_modules/rollup/dist/shared/rollup.js:17237:26)
------
executor failed running [/bin/sh -c npm run build-client]: exit code: 1

**Comment by root-deeptown** [comment]
P.S: master branch.

**Comment by HexaField** [comment]
Hello, are you still facing this problem?
