### ISSUE TITLE
Docker Backend and JS frontend for Ripple Grant (XRPL, IPFS), ILP & Coil

### ISSUE THREAD

**Issue by mrhegemon** [XRFoundation/XREngine#5531]
Add containers to helm chart and make sure they are working (rippled, go-ipfs, ilp something)

Add coil and ilp connector (?) to client

Might be best to break this down into smaller isssues!

xrpl docker
https://hub.docker.com/u/xrpllabsofficial
old?
https://twitter.com/xrpllabs/status/1431756688676241418

https://github.com/WietseWind/docker-rippled
https://github.com/WietseWind/docker-rippled-validator

ipfs docker - add file driver alt / no S3
https://docs.ipfs.io/how-to/run-ipfs-inside-docker/
https://github.com/yeasy/docker-ipfs
https://hub.docker.com/r/ipfs/go-ipfs/

coil
https://coil.com/creator/how-to-monetize

ilp
https://interledger.org/
https://hub.docker.com/u/interledgerjs
https://github.com/interledgerjs/ilp-connector

**Comment by dmitrizagidulin** [comment]
Further notes from convo with Liam:
* Add a 'Enable Coil' settings in admin panel. Add a textbox for the coil address.

**Comment by mrhegemon** [comment]
we need to make it configurable
enable ipfs as a file driver - deployment config
enable coil - an admin config
enable xrpl nodes  - deployment config
