### ISSUE TITLE
Invite to Party throwing error

### ISSUE THREAD

**Issue by zulqarnainhanif** [XRFoundation/XREngine#5573]
If a user is invited to a party then we get an error in console as shown in the screenshot below:

Probably occurring with GUEST users

<img width="587" alt="Screenshot 2022-03-29 at 1 46 12 PM" src="https://user-images.githubusercontent.com/30355034/160572335-03b86503-a4ce-4e92-b019-f89875796243.png">

**Comment by kinjalravel** [comment]
@HexaField In order to invite a user into party  we need party ID now currently party id is not available so from where Party Id will be fetched/retrieved in order to send the invitation ?
