### ISSUE TITLE
Editor error when loading models

### ISSUE THREAD

**Issue by Griffisaurus** [XRFoundation/XREngine#5576]
On production and dev, there is an "error loading from URL" on the editor UI and a failure to upload in console.  See screenshot.  Tried to load the allison.glb and razer laptop models with the same result.

![image](https://user-images.githubusercontent.com/92340542/160676955-9dffa97f-fd65-451f-af0c-048b235c4c66.png)

**Comment by NPatel10** [comment]
I made some changes in #5595, it started to work. One thing to be noted in the screenshot provided is that there is double `//` in the URL after the domain name. Maybe some env variable typo!!
