### ISSUE TITLE
GLB avatar not uploading 

### ISSUE THREAD

**Issue by Griffisaurus** [XRFoundation/XREngine#5577]
When trying to use an uploaded glb avatar (ready player me) from file, the animated avatar thumbnail loads but cannot complete the upload command.

![image](https://user-images.githubusercontent.com/92340542/160677578-4c9a4dab-418c-43a3-8b6c-0fd31ab1f556.png)

**Comment by HexaField** [comment]
this is because `uploadAvatarModel` does not use an XHR POST request, we need to refactor this command to use the currently unused `uploadStaticResource`
