### ISSUE TITLE
[Editor] Installed Projects not loading

### ISSUE THREAD

**Issue by zulqarnainhanif** [XRFoundation/XREngine#5589]
Just move to /editor route and refresh, the installed project won't load.

if you open /editor/default-project it will load perfectly fine and when you quit from there it will show installed projects and after refresh they will be gone again.

<img width="1478" alt="Screenshot 2022-03-31 at 2 09 34 AM" src="https://user-images.githubusercontent.com/30355034/160931511-2bd0971b-d8cd-45dd-b191-082f590021ed.png">

**Comment by NPatel10** [comment]
Can you provide more steps to regenerate it. I am not able do that on `local` as well as on `dev` server?

**Comment by zulqarnainhanif** [comment]
was some glitch in my Branch probably, unable to reproduce it again.
