### ISSUE TITLE
Style scroll bars in editor

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#5593]
they're a little boring!
![Screenshot from 2022-03-31 15-28-16](https://user-images.githubusercontent.com/10372036/160976713-a3987e1b-374f-48a7-b9ad-477f284be1e1.png)

**Comment by HexaField** [comment]
![scrollbar-styling](https://user-images.githubusercontent.com/10372036/160976921-2f85d4b4-3368-4000-97da-c043b71c0a9a.jpg)
something fancy like the one with the gradient, third from the left, with out pink to purple gradient we use elsewhere would make this pop quite a lot.

**Comment by kinjalravel** [comment]
@HexaField  How's look this?

<img width="333" alt="Screenshot 2022-03-31 at 2 33 55 PM" src="https://user-images.githubusercontent.com/41296632/161018924-7d213c4f-539a-49db-973d-e7edfec86f1f.png">

**Comment by zulqarnainhanif** [comment]
> @HexaField How's look this?
> 
> <img alt="Screenshot 2022-03-31 at 2 33 55 PM" width="333" src="https://user-images.githubusercontent.com/41296632/161018924-7d213c4f-539a-49db-973d-e7edfec86f1f.png">

Can you try with top to bottom gradient?

**Comment by HexaField** [comment]
Yep let's use the top to bottom gradient as @zulqarnainhanif says.
