### ISSUE TITLE
Github sync, project specific write & read scopes

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#5613]
PR to be reviewed by @hanzlamateen - Hanzla, please message him when this branch is ready for review.

Version 1: Github sync, basic public/private permissions

User Paths

- Connect to GitHub, get write scopes
  - When pulling / pushing, it tries the deployment's github credentials, 
  - if fails it tries your account's github credentials, 
  - if you have no github connection, it kicks off a github oauth request w/ the right scopes,
  - if not, throws an error

- Connect a project to a new or existing repo
- Handle public/private permissions
- Import from github
- Update from Github
- Commit + Push to GitHub

Maybe a progress bar for all of this? Toast notification when things are started/done?

Project Metadata - project table

Public / Private
- Public - All can see, admin/author can edit
- Private - admin/author can see/edit

Owner
- User ID 

Github
- Repo URL

UI updates: https://www.figma.com/file/uMPIoXOY1kJiG6UnqRJn8O/Project-UI?node-id=0%3A1

Version 2, project specific write & read scopes for users
example: `project:XREngine-Project-e-commerce:read`

**Comment by mrhegemon** [comment]
![image](https://user-images.githubusercontent.com/5104160/173465532-2f752622-44d5-44f7-a433-ca0fa56a162e.png)
![image](https://user-images.githubusercontent.com/5104160/173465545-0a16cf2b-beea-4f06-9bf0-e5f3208a2d75.png)
