### ISSUE TITLE
[Story] Convert all location UI to ethereal

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#5647]
PR to be reviewed by @speigg - Gheric please message him when this branch is ready for review.

For now, lets just throw all the relevant UI buttons into a single panel.
- [x] Main Menu Button UI
- [x] Main Menu Button State
- [x] Main Menu Button System to display buttons on click
- [x] Share menu UI
- [x] Share menu System
- [x] Setting menu UI
- [x] Setting menu System
- [ ] Emote menu UI
- [x] Emote menu System
- [x] Chat menu UI
- [x] Chat menu System
- [ ] Profile menu UI
- [ ] Profile menu System
- [ ] Avatar select menu UI
- [ ] Avatar select menu System
- [ ] Avatar upload menu UI
- [ ] Avatar upload menu System
- [x] enable/disable audio button 
- [x] exit VR button
- [x] respawn button

This panel will be attached to the user's left hand, pressing the left joystick down will toggle it on and off.
When a button is clicked, it opens that menu, we can use the same designs we already have, adding a back button.

https://github.com/XRFoundation/XREngine/issues/5927

**Comment by zulqarnainhanif** [comment]
> @HexaField ethereal UI is the same right that I have used to create context menu?

Yeap

**Comment by HexaField** [comment]
The main menu issue can be tracked from https://github.com/XRFoundation/XREngine/issues/6085 this is the XRUI component that shows all the icons. For desktop and mobile, these will exist as a list similarly to how the four purple buttons current work, and in VR will be a grid that appears above the user's wrist
