### ISSUE TITLE
Files not loading from editor CMS

### ISSUE THREAD

**Issue by Griffisaurus** [XRFoundation/XREngine#5736]
can’t drag files from the file explore into the scene.  Results in an invalid URL for images and models. Tried this with the glb and png.  File import seems completely broken
![unnamed](https://user-images.githubusercontent.com/92340542/163268320-dfb8595b-bf5d-47c8-9683-6c4ec0eeecbc.png)

**Comment by NPatel10** [comment]
@Griffisaurus, I tried to recreate this issue in local with S3 and local storage, I also tried on `dev` environment but still not able to recreate. can you provide exact steps or is there any file for which it is not working?
