### ISSUE TITLE
file upload broken

### ISSUE THREAD

**Issue by Griffisaurus** [XRFoundation/XREngine#5737]
Attempted to drag ecommerce models (keyboard used in demo) into the editor.  Uploading files status but never finished
![unnamed (1)](https://user-images.githubusercontent.com/92340542/163268506-297e84cc-734f-49b4-89c6-a896e9825e81.png)

**Comment by dinomut1** [comment]
![brave_tslOPiIre5](https://user-images.githubusercontent.com/94419856/164070286-ee7c36c1-abdf-4bff-b2a6-a8e0605097f0.png)
![brave_EiApPtQAx6](https://user-images.githubusercontent.com/94419856/164070290-abd5d73e-5df8-4a1e-ac7d-cc62d7e04014.png)

Resolving the URL from resource.dev.theoverlay is adding an extra forward slash
