### ISSUE TITLE
Can’t save scene in editor

### ISSUE THREAD

**Issue by Griffisaurus** [XRFoundation/XREngine#5739]

**Comment by HexaField** [comment]
Can i get some clarification on what exactly the issue is here?

**Comment by speigg** [comment]
![image](https://user-images.githubusercontent.com/507127/164069878-de1bf283-6843-4151-8367-df164c578377.png)

**Comment by dinomut1** [comment]
Also, looking at the screenshot, the Cubemap texture url is a resources.dev.theoverlay URL which will be broken by issue https://github.com/XRFoundation/XREngine/issues/5737

**Comment by speigg** [comment]
Another error someone is seeing: 

Cannot read properties of undefined (reading 'composed')
