### ISSUE TITLE
avatar thumbnail broken

### ISSUE THREAD

**Issue by Griffisaurus** [XRFoundation/XREngine#5742]
Some avatar thumbnails still broken or have odd placement.

![image](https://user-images.githubusercontent.com/92340542/163270317-3270eb5d-1e57-40fa-9a2c-ae6e8e2af713.png)

**Comment by HexaField** [comment]
The odd positoining is due to user error, it generates the thumbnail when you click the upload button.

**Comment by HexaField** [comment]
I need more information about the missing thumbnail
