### ISSUE TITLE
Avatar test scene

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#5831]
We should add a testbed page in the development suite project that shows a grid of the following:

Columns of each avatar
Rows for each avatar showing:
- retargeted avatar with animations
- no material with skeleton helper
- t pose white shaded material

**Comment by rondoor124** [comment]
@HexaField 
Currently, this unit test has only retargeting and bone matching test parts for only glb files.
Please let me know if we need more updates.
Thanks
