### ISSUE TITLE
Refreshing default-project may not be sourcing from GH

### ISSUE THREAD

**Issue by barankyle** [XRFoundation/XREngine#5892]
I refreshed default-project on prod before anything had been deployed, and xrengine.config,ts didn't have the removal of the /examples route reflected in S3. The S3 files had definitely just been updated. I wonder if it's uploading the local copy instead of pulling from GH?

**Comment by HexaField** [comment]
Yes, it has been implemented this way

```ts
// project.class.ts
async update(data: { url: string }, params?: Params) {
  if (data.url === 'default-project') {
    copyDefaultProject()
    await uploadLocalProjectToProvider('default-project')
    return
  }
// ...
```
