### ISSUE TITLE
View avatar in admin panel does not show avatar

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#5898]
![Screenshot from 2022-04-29 11-01-34](https://user-images.githubusercontent.com/10372036/165870543-29c40897-da4f-4551-8727-79492435a78b.png)
![Screenshot from 2022-04-29 11-02-47](https://user-images.githubusercontent.com/10372036/165870589-c214249e-261c-48e4-89a8-e5757c0f1a6d.png)

retargeting error

**Comment by zulqarnainhanif** [comment]
@HexaField this issue is occurring while uploading the avatar file as well, have tested from the location route as well.

**Comment by HexaField** [comment]
> @HexaField this issue is occurring while uploading the avatar file as well, have tested from the location route as well.

yes, they both use the same modal
