### ISSUE TITLE
Mobile UI Scaling

### ISSUE THREAD

**Issue by Griffisaurus** [XRFoundation/XREngine#5915]
Mobile UI is not centered and the scale is off.  Not all UI elements, but profile modal and avatar selection is off.

![image](https://user-images.githubusercontent.com/92340542/166079086-e3ff0535-de90-44fd-9b57-1ba4d6bf3ff9.png)

**Comment by HexaField** [comment]
![Screenshot_20220524-094021_Brave](https://user-images.githubusercontent.com/10372036/169921194-e0d5f4ce-2a01-40d1-b96c-8ac3d6fc8f1b.jpg)
