### ISSUE TITLE
Cleanup static-resource table and create avatar table in DB

### ISSUE THREAD

**Issue by speigg** [XRFoundation/XREngine#5958]
We should have a dedicated `avatar` table, with `id`, `name`, `modelResourceId`, and `thumbnailResourceId` columns. 

The `static-resource` table needs to be normalized; it should only contain these keys: `id, url, mimeType, createdAt, updatedAt, statusCode`. Everything else should be moved into separate tables (if needed).

**Comment by barankyle** [comment]
Avatars should have display name (non unique) and slugified identifier, which is UUID of avatar plus slugified name. slugified identifer is used to name files.
