### ISSUE TITLE
Fix editor movement

### ISSUE THREAD

**Issue by speigg** [XRFoundation/XREngine#5991]
Bug: editor movement doesn't always work. Regression is caused by this commit: 
https://github.com/XRFoundation/XREngine/commit/0662f67bb162da0abdd72ccd8b0ecf486cee3ef3

To reproduce: 
Go directly to a scene url in the editor https://dev.theoverlay.io/editor/default-project/apartment
Or, load a project with only one scene

**Comment by HexaField** [comment]
```
TypeError: Cannot set properties of null (setting 'isOrbiting')
    at EditorControlSystem.ts:523:25
    ```
