### ISSUE TITLE
number of names shown does not match UI for users

### ISSUE THREAD

**Issue by Griffisaurus** [XRFoundation/XREngine#6005]
pages say different number of users shown than actual

![image](https://user-images.githubusercontent.com/92340542/167475120-39681457-a76d-418d-93cc-bd35e946b3a7.png)

**Comment by zulqarnainhanif** [comment]
@Griffisaurus i have investigated the feature in detail, I think this issue is fixed with a fix which i believe @barankyle worked on regarding server queries. Please close this issue if it doesn't persists any more.
