### ISSUE TITLE
Push Project Modifications to Github Repo from Editor

### ISSUE THREAD

**Issue by dinomut1** [XRFoundation/XREngine#6014]
Currently the engine doesn't have a way to push updates to a project back to its github repo. We need a way to push changes made in dev to the repo, so that when deploying to production it doesn't have missing changes.

**Comment by dinomut1** [comment]
This could either be a button in admin, or automatically happens on save

**Comment by HexaField** [comment]
related PR https://github.com/XRFoundation/XREngine/issues/4009

**Comment by HexaField** [comment]
duplicate of https://github.com/XRFoundation/XREngine/issues/4009
