### ISSUE TITLE
Saving in the editor causes it to freeze and pixelate

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#6037]

**Comment by HexaField** [comment]
The pixelation has been fixed, but I am still unable to move the camera or click on things after saving the scene.

**Comment by NPatel10** [comment]
@HexaField, I did encounter the saving issue but now after the Postprocessing PR is merged I am not able to regenerate it. Can you confirm on your end?

**Comment by HexaField** [comment]
> @HexaField, I did encounter the saving issue but now after the Postprocessing PR is merged I am not able to regenerate it. Can you confirm on your end?

it seems to still be there for scenes that do not have a post processing node.
