### ISSUE TITLE
error in https://192.168.0.15:8642/ my local ip

### ISSUE THREAD

**Issue by johnfelipe** [XRFoundation/XREngine#6244]
npm run dev

this is log:

	> xrengine@0.0.0 dev
	> npm run dev-docker && concurrently -n agones,server,client npm:dev-agones-silent npm:dev-server npm:dev-client

	> xrengine@0.0.0 dev-docker
	> cd scripts && docker-compose up -d

	elasticsearch is up-to-date
	xrengine_redis is up-to-date
	xrengine_test_db is up-to-date
	xrengine_minikube_db is up-to-date
	xrengine_db is up-to-date
	kibana is up-to-date
	[server]
	[server] > xrengine@0.0.0 dev-server
	[server] > cd packages/server && npm run dev
	[server]
	[agones]
	[agones] > xrengine@0.0.0 dev-agones-silent
	[agones] > npm run dev-agones &> /dev/null
	[agones]
	[client]
	[client] > xrengine@0.0.0 dev-client
	[client] > cd packages/client && npm run dev
	[client]
	[server]
	[server] > @xrengine/server@0.5.6 dev
	[server] > cross-env APP_ENV=development concurrently -n server,gameserver,mediaserver,files "ts-node-dev --inspect --respawn --transpile-only  src/index.ts" "cd ../gameserver && npm run dev" "cd ../gameserver && npm run dev-channel" "npm run serve-local-files"
	[server]
	[client]
	[client] > @xrengine/client@0.5.6 dev
	[client] > cross-env APP_ENV=development vite
	[client]
	[agones]
	[agones] > xrengine@0.0.0 dev-agones
	[agones] > cd scripts && ./start-agones.sh
	[agones]
	[agones] Starting Agones sidecar for local development on Linux...
	[agones] {"ctlConf":{"Address":"localhost","IsLocal":true,"LocalFile":"","Delay":0,"Timeout":0,"Test":"","TestSdkName":"","GRPCPort":9357,"HTTPPort":9358},"featureGates":"ContainerPortAllocation=true\u0026Example=true\u0026PlayerTracking=false\u0026SDKWatchSendOnExecute=false","message":"Starting sdk sidecar","severity":"info","source":"main","time":"2022-05-28T21:28:58.224525791Z","version":"1.8.0"}
	[agones] {"grpcEndpoint":"localhost:9357","message":"Starting SDKServer grpc service...","severity":"info","source":"main","time":"2022-05-28T21:28:58.230078265Z"}
	[agones] {"httpEndpoint":"localhost:9358","message":"Starting SDKServer grpc-gateway...","severity":"info","source":"main","time":"2022-05-28T21:28:58.234513727Z"}
	[server] [gameserver]
	[server] [gameserver] > @xrengine/gameserver@0.5.6 dev
	[server] [gameserver] > cross-env APP_ENV=development ts-node-dev --inspect=2995 --respawn --transpile-only src/index.ts
	[server] [gameserver]
	[server] [server] [INFO] 21:28:59 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.6.2)
	[server] [files]
	[server] [files] > @xrengine/server@0.5.6 serve-local-files
	[server] [files] > http-server ./upload --ssl --cert ../../certs/cert.pem --key ../../certs/key.pem --port 8642 --cors=*
	[server] [files]
	[server] [server] Debugger listening on ws://127.0.0.1:9229/ab38e8f4-7991-4ef9-94f5-a6b92d7318b5
	[server] [server] For help, see: https://nodejs.org/en/docs/inspector
	[server] [mediaserver]
	[server] [mediaserver] > @xrengine/gameserver@0.5.6 dev-channel
	[server] [mediaserver] > APP_ENV=development cross-env GAMESERVER_PORT=3032 ts-node-dev --inspect=2996 --respawn --transpile-only src/index.ts
	[server] [mediaserver]
	[server] [files] Starting up http-server, serving ./upload through https
	[server] [files]
	[server] [files] http-server version: 14.1.0
	[server] [files]
	[server] [files] http-server settings:
	[server] [files] CORS: *
	[server] [files] Cache: 3600 seconds
	[server] [files] Connection Timeout: 120 seconds
	[server] [files] Directory Listings: visible
	[server] [files] AutoIndex: visible
	[server] [files] Serve GZIP Files: false
	[server] [files] Serve Brotli Files: false
	[server] [files] Default File Extension: none
	[server] [files]
	[server] [files] Available on:
	[server] [files]   https://127.0.0.1:8642
	[server] [files]   https://192.168.0.15:8642 
	[server] [files]   https://172.18.0.1:8642
	[server] [files] Hit CTRL-C to stop the server
	[server] [files]
	[client] [vite.config.js]: Failed to read clientSetting
	[client] Error
	[client]     at Query.run (/root/XREngine/node_modules/sequelize/dist/lib/dialects/mysql/query.js:52:25)
	[client]     at /root/XREngine/node_modules/sequelize/dist/lib/sequelize.js:313:28
	[client]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
	[client]     at async MySQLQueryInterface.select (/root/XREngine/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:396:12)
	[client]     at async Function.findAll (/root/XREngine/node_modules/sequelize/dist/lib/model.js:1119:21)
	[client]     at async getClientSetting (/root/XREngine/packages/client/vite.config.js:161:25)
	[client]     at async /root/XREngine/packages/client/vite.config.js:235:25
	[client]     at async loadConfigFromFile (/root/XREngine/node_modules/vite/dist/node/chunks/dep-2fd39086.js:61617:24)
	[client]     at async resolveConfig (/root/XREngine/node_modules/vite/dist/node/chunks/dep-2fd39086.js:61142:28)
	[client]     at async createServer (/root/XREngine/node_modules/vite/dist/node/chunks/dep-2fd39086.js:58982:20) {
	[client]   name: 'SequelizeDatabaseError',
	[client]   parent: Error: Table 'xrengine.clientSetting' doesn't exist
	[client]       at Packet.asError (/root/XREngine/node_modules/mysql2/lib/packets/packet.js:728:17)
	[client]       at Query.execute (/root/XREngine/node_modules/mysql2/lib/commands/command.js:29:26)
	[client]       at Connection.handlePacket (/root/XREngine/node_modules/mysql2/lib/connection.js:456:32)
	[client]       at PacketParser.onPacket (/root/XREngine/node_modules/mysql2/lib/connection.js:85:12)
	[client]       at PacketParser.executeStart (/root/XREngine/node_modules/mysql2/lib/packet_parser.js:75:16)
	[client]       at Socket.<anonymous> (/root/XREngine/node_modules/mysql2/lib/connection.js:92:25)
	[client]       at Socket.emit (node:events:527:28)
	[client]       at addChunk (node:internal/streams/readable:315:12)
	[client]       at readableAddChunk (node:internal/streams/readable:289:9)
	[client]       at Socket.Readable.push (node:internal/streams/readable:228:10) {
	[client]     code: 'ER_NO_SUCH_TABLE',
	[client]     errno: 1146,
	[client]     sqlState: '42S02',
	[client]     sqlMessage: "Table 'xrengine.clientSetting' doesn't exist",
	[client]     sql: 'SELECT `id`, `logo`, `title`, `url`, `releaseName`, `siteDescription`, `favicon32px`, `favicon16px`, `icon192px`, `icon512px`, `createdAt`, `updatedAt` FROM `clientSetting` AS `clientSetting`;',
	[client]     parameters: undefined
	[client]   },
	[client]   original: Error: Table 'xrengine.clientSetting' doesn't exist
	[client]       at Packet.asError (/root/XREngine/node_modules/mysql2/lib/packets/packet.js:728:17)
	[client]       at Query.execute (/root/XREngine/node_modules/mysql2/lib/commands/command.js:29:26)
	[client]       at Connection.handlePacket (/root/XREngine/node_modules/mysql2/lib/connection.js:456:32)
	[client]       at PacketParser.onPacket (/root/XREngine/node_modules/mysql2/lib/connection.js:85:12)
	[client]       at PacketParser.executeStart (/root/XREngine/node_modules/mysql2/lib/packet_parser.js:75:16)
	[client]       at Socket.<anonymous> (/root/XREngine/node_modules/mysql2/lib/connection.js:92:25)
	[client]       at Socket.emit (node:events:527:28)
	[client]       at addChunk (node:internal/streams/readable:315:12)
	[client]       at readableAddChunk (node:internal/streams/readable:289:9)
	[client]       at Socket.Readable.push (node:internal/streams/readable:228:10) {
	[client]     code: 'ER_NO_SUCH_TABLE',
	[client]     errno: 1146,
	[client]     sqlState: '42S02',
	[client]     sqlMessage: "Table 'xrengine.clientSetting' doesn't exist",
	[client]     sql: 'SELECT `id`, `logo`, `title`, `url`, `releaseName`, `siteDescription`, `favicon32px`, `favicon16px`, `icon192px`, `icon512px`, `createdAt`, `updatedAt` FROM `clientSetting` AS `clientSetting`;',
	[client]     parameters: undefined
	[client]   },
	[client]   sql: 'SELECT `id`, `logo`, `title`, `url`, `releaseName`, `siteDescription`, `favicon32px`, `favicon16px`, `icon192px`, `icon512px`, `createdAt`, `updatedAt` FROM `clientSetting` AS `clientSetting`;',
	[client]   parameters: {}
	[client] }
	[client] failed to load config from /root/XREngine/packages/client/vite.config.js
	[client] error when starting dev server:
	[client] TypeError: Cannot read properties of undefined (reading 'title')
	[client]     at /root/XREngine/packages/client/vite.config.js:250:32
	[client]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
	[client]     at async loadConfigFromFile (/root/XREngine/node_modules/vite/dist/node/chunks/dep-2fd39086.js:61617:24)
	[client]     at async resolveConfig (/root/XREngine/node_modules/vite/dist/node/chunks/dep-2fd39086.js:61142:28)
	[client]     at async createServer (/root/XREngine/node_modules/vite/dist/node/chunks/dep-2fd39086.js:58982:20)
	[client]     at async CAC.<anonymous> (/root/XREngine/node_modules/vite/dist/node/cli.js:688:24)
	[client] npm ERR! Lifecycle script `dev` failed with error:
	[client] npm ERR! Error: command failed
	[client] npm ERR!   in workspace: @xrengine/client@0.5.6
	npm ERR!   at location: /root/XREngine/packages/client
	[client] npm run dev-client exited with code 1
	[server] [gameserver] [INFO] 21:28:59 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.6.2)
	[server] [gameserver] Debugger listening on ws://127.0.0.1:2995/eade694b-f88a-409e-a82b-6754b1515956
	[server] [gameserver] For help, see: https://nodejs.org/en/docs/inspector
	[server] [mediaserver] [INFO] 21:28:59 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.6.2)
	[server] [mediaserver] Debugger listening on ws://127.0.0.1:2996/085668a5-59ce-4cc0-98e9-bfee79896089
	[server] [mediaserver] For help, see: https://nodejs.org/en/docs/inspector

**Comment by johnfelipe** [comment]
solved

**Comment by orange-No1** [comment]
How did you solve this problem?
