### ISSUE TITLE
File Browser shows edited files and can manage commits, branch & push to a remote

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#6280]
![Screenshot from 2022-06-01 17-48-49](https://user-images.githubusercontent.com/10372036/171354919-48da68ef-9d0d-41ed-aa5d-76802c32539d.png)

**Comment by HexaField** [comment]
![Screenshot from 2022-06-01 18-06-30](https://user-images.githubusercontent.com/10372036/171357745-faa9f686-4aa8-4175-91b0-637f08fa1c5b.png)

**Comment by speigg** [comment]
Simpler alternative https://github.com/XRFoundation/XREngine/issues/6287
