### ISSUE TITLE
[Story] Panel UI mode for media session view

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#6326]
We want a conference mode, which can easily be turned on and off with a button at the top of the bubbles. This will open a full screen UI that has each of the participants as shown below.

Can do this with a flex box.

![pronouns-zoom-1-1820x958](https://user-images.githubusercontent.com/10372036/171342099-89b7bad5-e55d-4432-8d14-e7dde98da277.jpg)

**Comment by johnfelipe** [comment]
What about implement Jitsi meet?

**Comment by johnfelipe** [comment]
That sounds great, this feature how many time for testing?
