### ISSUE TITLE
[Bug]: with update not retain locations

### ISSUE THREAD

**Issue by johnfelipe** [XRFoundation/XREngine#6344]

**Comment by HexaField** [comment]
Please provide more information

**Comment by johnfelipe** [comment]
i do this:

	sudo su
	cd
	cd XREngine/
	git pull
	npm i
	npm run dev-reinit
	npm run dev

and location latest is gone
and avatar gone to

**Comment by HexaField** [comment]
right, `npm run dev-reinit` will wipe the database. you need to use a custom project (not the default project) to store project files
