### ISSUE TITLE
[Story] Add 'party' UI

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#6360]
- [ ] list users in the party
- [ ] if the user is the party host, they can kick users from the party
- [ ] host can invite users to the party

![Screenshot from 2022-06-07 09-27-03](https://user-images.githubusercontent.com/10372036/172267914-62ce4189-ca69-4138-9d82-bee3f0dfbe6e.png)

**Comment by speigg** [comment]
![Uploading image.png…]()
