### ISSUE TITLE
[Story] Spectator View

### ISSUE THREAD

**Issue by Griffisaurus** [XRFoundation/XREngine#6377]
PR to be reviewed by @mrhegemon - Liam, please message him when this branch is ready for review.

Virtual worlds have many uses and many do not require physical presence for all participants.

**Describe the solution you'd like**
Create a spectator mode.  The player with a physical presence sends a spectator invite URL.  Once the invited person clicks the URL, they are brought into the location with their camera attached to the avatar of the person they received the invite from.  They need to still be able to use voice, video, text chat and create and account but they do not have an avatar.

**Describe alternatives you've considered**
tour guide spline, ability for a party leader to gather others in the party in the direction they are facing.

**Comment by mrhegemon** [comment]
my crude idea for a spectator invite
![image](https://user-images.githubusercontent.com/5104160/174907248-97b1ff66-6950-442b-a8bb-4e949ba8910d.png)
Add a checkbox to the invite screen on the client and the admin invite system.
