### ISSUE TITLE
[Bug]: Avatar material transparency glitching

### ISSUE THREAD

**Issue by Griffisaurus** [XRFoundation/XREngine#6385]
PR to be reviewed by @speigg - Gheric, please message him when this branch is ready for review.

Some avatar materials showing transparent.  

![image](https://user-images.githubusercontent.com/92340542/172963860-584cba3b-7f93-4fad-906f-e9eb0cddbad4.png)

![image](https://user-images.githubusercontent.com/92340542/172964248-87eb6c96-230e-41a5-86d6-8fa2f80dbf3a.png)

**Comment by rondoor124** [comment]
I find out this issue is related to the head decapitation shader material.
I will check out the details and fix it soon.
