### ISSUE TITLE
[Bug]: Avatar upload does not work in admin panel

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#6405]
PR to be reviewed by @dinomut1 - David, please message him when this branch is ready for review.

**Comment by hanzlamateen** [comment]
This appears to be working fine for valid avatar files location in `packages/projects/default-project/public/avatars/`
Tested againt the latest code [c7820aa](https://github.com/XRFoundation/XREngine/commit/c7820aa2b966bb170d6eba1599c31fae8ae92b16)
