### ISSUE TITLE
[Bug]: Error on sort location in user table of admin panel

### ISSUE THREAD

**Issue by hanzlamateen** [XRFoundation/XREngine#6411]
The below error is thrown. It seems like an issue with backend sql query throwing the error.

![image](https://user-images.githubusercontent.com/10975502/173403966-0cefb59a-09ca-4d11-8d73-63c9c4d59994.png)

**Comment by HexaField** [comment]
need to check if this is still a problem

**Comment by hanzlamateen** [comment]
This issue is still there on repeatedly applying sort by location filter on users table

![image](https://user-images.githubusercontent.com/10975502/182511324-d969134b-7317-4c8e-9d37-e006d3858f35.png)
