### ISSUE TITLE
[Bug]: Jumping animation broken

### ISSUE THREAD

**Issue by Griffisaurus** [XRFoundation/XREngine#6433]
PR to be reviewed by @speigg - Gheric, please message him when this branch is ready for review.

Jumping animation timing is off.  Animation only starts just before hitting the ground on fall.  Screenshot is from the apex of a jump.

![image](https://user-images.githubusercontent.com/92340542/173869803-e373aeeb-3186-4355-a2c6-bf70ee2860ea.png)

**Comment by speigg** [comment]
I have not been able to reproduce any jumping issues
