### ISSUE TITLE
[Bug]: Default colors still suck in most places

### ISSUE THREAD

**Issue by mrhegemon** [XRFoundation/XREngine#6494]
Homepage GREAT:
![image](https://user-images.githubusercontent.com/5104160/175650401-b83708d4-b63a-4d4c-a472-12564c85317a.png)

Great dark gradient with white text, color gradients 

HIGHLIGHT COLORS
We could use some highlights in our scene, 

Let's add some, a little of the "vaporwave"

These scroll bars are hot
![image](https://user-images.githubusercontent.com/5104160/175650649-63778ff1-54cf-4463-ac76-7a3fadcd7c8f.png)

Editor project page - looking good but could use highlight gradient on the [create] button
![image](https://user-images.githubusercontent.com/5104160/175650841-12ed0711-4e12-4444-91f5-ed59df3cd5c6.png)

Editor 

Do the opposite

bank background should be near white #CCCCCC or something
The windows and top bar should be near black #333333 or something

Vaporwave highlights would be great
![image](https://user-images.githubusercontent.com/5104160/175651107-737e23f4-25f9-4ddc-ba85-013b3c8e7c60.png)

**Comment by mrhegemon** [comment]
![image](https://user-images.githubusercontent.com/5104160/175652766-ba9e6146-6568-403d-8956-b90cb41ef5d6.png)

**Comment by mrhegemon** [comment]
The admin panel looks great, could use a little more highlight

![image](https://user-images.githubusercontent.com/5104160/175653175-2d799f63-3b22-4bfc-9e6e-5a287aaa5dbb.png)

Same with the client

**Comment by HexaField** [comment]
The greyscale here is just what I set it to somewhat rushed, we have this tracked in this issue https://github.com/XRFoundation/XREngine/issues/6439

**Comment by hanzlamateen** [comment]
@mrhegemon can you elaborate what should be done for your below comment in description?
`Editor project page - looking good but could use highlight gradient on the [create] button`

**Comment by hanzlamateen** [comment]
@mrhegemon dark mode in editor after color changes. Any comments/changes?
![image](https://user-images.githubusercontent.com/10975502/177707945-78e59a94-f873-4898-9a78-5b78ad2fd503.png)

**Comment by hanzlamateen** [comment]
![image](https://user-images.githubusercontent.com/10975502/177709963-8d89e589-1940-47f1-a424-83e0c6df8490.png)

**Comment by hanzlamateen** [comment]
Option 2: More darker background so that the buttons on the top bar stands out which is not the case in Option 1.

![image](https://user-images.githubusercontent.com/10975502/177710912-2114f614-b9cd-4774-ba1c-33e9a93656cd.png)

**Comment by mrhegemon** [comment]
Option 2 is much better. Do that.
