### ISSUE TITLE
Keymap Diagram in 3d at spawn point

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#6696]
- In figma, can put in Settings and in 3D space in world

**Comment by mrhegemon** [comment]
![image](https://user-images.githubusercontent.com/5104160/182492281-ef4c321d-f70f-4206-817b-c38029d9f074.png)
![image](https://user-images.githubusercontent.com/5104160/182492300-ff9eab6a-8616-46bb-b3df-8713af85f77c.png)
