### ISSUE TITLE
[Bug]: Avatar files from storage are not deleted

### ISSUE THREAD

**Issue by hanzlamateen** [XRFoundation/XREngine#6722]
When we delete an avatar from the admin panel's avatars section, its entry from database table `static_resource` is deleted. But the physical files (avatar & thumbnail) are not deleted from storage.

We also need to ensure if any user in the `user` table has `avatarId` of deleted avatar being assigned, then it doesnt create issue while loading the user in a location.

**Comment by barankyle** [comment]
I think I fixed this as part of #6736
