### ISSUE TITLE
[Epic]: Migrate to tailwindcss

### ISSUE THREAD

**Issue by speigg** [XRFoundation/XREngine#6737]
Separation of concerns between html and css works fine for documents, not so much for complex web apps. Our current approach leads to bloated stylesheets and is simply not feasible to maintain well at scale. We should consider migrating to tailwind.css

https://adamwathan.me/css-utility-classes-and-separation-of-concerns/

**Comment by HexaField** [comment]
https://github.com/XRFoundation/XREngine/issues/6485
