### ISSUE TITLE
Smart CPU and GPU memory disposal and re-caching from the ECS

### ISSUE THREAD

**Issue by mrhegemon** [XRFoundation/XREngine#6742]
Smart CPU and GPU memory disposal and re-caching from the ECS

https://tech-en.netlify.app/articles/en521470/index.html

**Comment by speigg** [comment]
This is what we need:

https://github.com/mrdoob/three.js/issues/9985
https://github.com/mrdoob/three.js/pull/9512

**Comment by speigg** [comment]
This is now partially done.

https://github.com/XRFoundation/XREngine/commit/cd422a3abc5def98f8d96a48ba4932c45bb368d6


However, we still have references to buffers and texture data in our AssetLoader in-memory cache. We should probably remove that functionality (we can rely on browser cache); I started to do this, however our scene loading logic depends in many places on how the AssetLoader currently works. We'll have to refactor our scene loading logic to allow for a more decoupled loading process.

**Comment by HexaField** [comment]
we should make a PR to threejs with these changes to the FBX loader, to both get their thoughts and  to offload to them for futureproofing

https://github.com/XRFoundation/XREngine/commit/cd422a3abc5def98f8d96a48ba4932c45bb368d6
