### ISSUE TITLE
Cleanup AR

### ISSUE THREAD

**Issue by speigg** [XRFoundation/XREngine#6763]
- 1st-person 
    - Locomotion: Avatar Attachment To camera position
    - Hide Avatar for local player ?
    - Life-size scene alignment / placement
- 3rd-person 
    - Locomotion: Avatar Detached from camera (moves via controls (e.g., joystick) based on camera direction)
    - Dollhouse Scene Placement
- Animate avatar arms correctly when XR controllers are missing
- also AR hittest & interaction rays

**Comment by mrhegemon** [comment]
also AR hittest & interaction rays
