### ISSUE TITLE
[Bug]: Can't close the ecommerce Ethereal UI window

### ISSUE THREAD

**Issue by dmitrizagidulin** [XRFoundation/XREngine#6766]
Replication steps:
* go to https://demo.etherealengine.com/location/shopping-district
* walk up to the Egg chair, hit E to interact, ecommerce window pops up

![image](https://user-images.githubusercontent.com/947005/184039939-4e322ba6-148b-415b-bb20-42c2abe7987e.png)

**Expected behavior:**  There should be an X icon in the top right (to close the window). Failing that, clicking outside the window should also close it.

**Actual behavior:**
Halp, I can't get out of the ecommerce window! No X icon, and clicking outside the window doesn't do anything either.

**Comment by speigg** [comment]
Pressing interact again, or walking away will close it, but we could certainly make it close if you click on the background too. None of our other UI has a close button, so I think we should match that convention.

**Comment by dmitrizagidulin** [comment]
Wrong repo; moving issue to https://github.com/TheOverlay/XREngine-Project-eCommerce/issues/16
