### ISSUE TITLE
Add Oembed with Thumbnail

### ISSUE THREAD

**Issue by mrhegemon** [XRFoundation/XREngine#6815]
https://embed.ly/providers/validate/oembed

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mrhegemon** [comment]
http://debug.iframely.com/?uri=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DFsr2fdoS1LA

**Comment by barankyle** [comment]
Links to locations should show a nice thumbnail, name of the location, title/subtitle of the deployment (e.g. [location name] - [site name] - [pretty domain])

Add oembed site headers
