### ISSUE TITLE
[Bug]: npm run dev-reinit needs to be ran twice when changing ip address

### ISSUE THREAD

**Issue by speigg** [XRFoundation/XREngine#6822]
When changing the ip address in local development, `npm run dev-reinit` needs to be ran twice, otherwise avatar assets ( e.g., `https://<ip>:8642/avatars/public/CyberbotGold_38c350a0-21a8-11ed-b3e4-b36ec0d803bc.glb` ) fail to load

**Comment by HexaField** [comment]
these should be being stored with an identifier that patches the storage provider, as we do with scene data and other assets

**Comment by barankyle** [comment]
What IPs are you switching between? I tried going between localhost (which I know doesn't work on Macs), 127.0.0.1, and 192.168.86.31, which is what my machine assigned as the local network IP, and one run of dev-reinit changed all of the static resource addresses as expected.

**Comment by speigg** [comment]
> What IPs are you switching between? 

Try changing your machine's actual local ip address on your LAN

**Comment by HexaField** [comment]
closing in favour of https://github.com/XRFoundation/XREngine/issues/7142
