### ISSUE TITLE
[Bug]: ERROR: "fatal: '-deployment' is not a valid branch name." when installing a project

### ISSUE THREAD

**Issue by speigg** [XRFoundation/XREngine#6823]
[server] [server] Cloning into 'common-avatars'...
[server] [server] origin
[server] [server] [1661138173773] INFO: origin
[server] [server] 
[server] [server]     component: "server-core"
[server] [server] fatal: '-deployment' is not a valid branch name.
[server] [server] [1661138173873] ERROR: fatal: '-deployment' is not a valid branch name.
[server] [server] 
[server] [server]     component: "server-core"
[server] [server]     err: {
[server] [server]       "type": "GitError",
[server] [server]       "message": "fatal: '-deployment' is not a valid branch name.\n",
[server] [server]       "stack":
[server] [server]           Error: fatal: '-deployment' is not a valid branch name.
[server] [server]           
[server] [server]               at Object.action (/Users/gheric/GitHub/xrengine/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)
[server] [server]               at PluginStore.exec (/Users/gheric/GitHub/xrengine/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)
[server] [server]               at /Users/gheric/GitHub/xrengine/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40
[server] [server]               at new TraceablePromise (/Users/gheric/GitHub/xrengine/node_modules/trace-unhandled/dist/lib/core.js:81:13)
[server] [server]               at GitExecutorChain.handleTaskData (/Users/gheric/GitHub/xrengine/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)
[server] [server]               at GitExecutorChain.<anonymous> (/Users/gheric/GitHub/xrengine/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)
[server] [server]               at Generator.next (<anonymous>)
[server] [server]               at fulfilled (/Users/gheric/GitHub/xrengine/node_modules/simple-git/dist/cjs/index.js:55:24)

**Comment by HexaField** [comment]
we probably just need to ignore the branch logic on local dev

**Comment by barankyle** [comment]
I was thinking of either just having 'local' be the default release name, and multiple local installations might overwrite each other in GH; or generating a consistent random string from some information unique to each machine to identify one local installation from another. Not sure we need to disable branch logic on local, since someone might want to push to GH from a local installation.

**Comment by speigg** [comment]
Can we pull it from `git config -l`, grab the user.name field, and name the branch `local-${gitUserName}>` ?
