### ISSUE TITLE
[UI] Chat barely readable

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#6863]
![Screenshot from 2022-09-02 13-50-58](https://user-images.githubusercontent.com/10372036/188055548-946f01eb-b7fa-48bc-a1c4-871698c833fd.png)

it also takes a few seconds for the chat to populate.

**Comment by hanzlamateen** [comment]
Added text shadow. Ref: https://github.com/XRFoundation/XREngine/commit/c3488a7d53740dfa265683d4ff05987300b1211f
