### ISSUE TITLE
Hybrid storage provider with IPFS

### ISSUE THREAD

**Issue by hanzlamateen** [XRFoundation/XREngine#6876]
We really just need multiple storage provider support, which comes down to just adding a storage provider ID to all storage provider related requests. Any time a static resource related thing is being CRUD'd, we need to specify which storage provider to use. We could have like storage provider classes, too, like local/s3 is "Private Storage" and ipfs/blockchain is "Decentralised Storage" and that's all we need to abstract for now.

**Comment by mrhegemon** [comment]
Do we want to seperate the asset ID and storage source? 

So we can easily track replication across different storage providers? And maybe allow you to move/copy in the future?



new optional parameter on POST and a property on GET

driver:ipfs/s3/local/cloudfront
