### ISSUE TITLE
[Bug]: Setting view appears squeezed when user is guest

### ISSUE THREAD

**Issue by hanzlamateen** [XRFoundation/XREngine#6932]
Here is how it appears when user is a guest:
![image](https://user-images.githubusercontent.com/10975502/189965197-2272a1d8-108e-4b66-aa21-2fdfba814eeb.png)

**Comment by barankyle** [comment]
Please also correct when a user gets logged out and, after re-signing in as a guest, the displayed view going from the profile panel to the settings panel. It should stay on the profile panel.

**Comment by hanzlamateen** [comment]
Screen recording of scenario please?

**Comment by barankyle** [comment]
https://user-images.githubusercontent.com/8977377/190280852-6f4860ec-0c05-4d6e-bf2c-fcf167a050a7.mp4
