### ISSUE TITLE
[Bug]: Engine.instance.isEditor being checked in MediaSystem before Engine.instance exists

### ISSUE THREAD

**Issue by barankyle** [XRFoundation/XREngine#6939]
On occasion, when loading seemingly any page (saw this on the homepage), the following error is being thrown:

`Uncaught TypeError: Cannot read properties of undefined (reading 'isEditor')
    at MediaSystem.ts:104:19`

In actuality, this is on line 97 of MediaSystem.ts.

**Comment by HexaField** [comment]
fixed in #f3de361
