### ISSUE TITLE
Editor - Basic Components

### ISSUE THREAD

**Issue by montage125** [XRFoundation/XREngine#7027]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/36287216/192552349-cba2bc18-e28f-438e-92ed-c604fc683ce0.png">
It is hoped that models can be created freely using various basic components in the editor

**Comment by montage125** [comment]
Real time rendering. While building, you can see the results. I hope there is a good editor

**Comment by HexaField** [comment]
The editor supports this.
