### ISSUE TITLE
[Bug]: minikube can't access localStorageProvider

### ISSUE THREAD

**Issue by barankyle** [XRFoundation/XREngine#7057]
If minikube is using localStorage as it storageProvider, it will be writing new files, such as those from projects that get added, to /app/packages/server/upload within the API pod handling the request. It does not write to the host's file system, which is the actual localStorage location. This is problematic, since those files will get wiped whenever the API pod is shut down, and static files from projects/avatars/etc. won't be accessible because they're not in the actual localStorage http-server.

There is a way to mount local file systems in minikube: https://stackoverflow.com/questions/48534980/mount-local-directory-into-pod-in-minikube

It seems like it needs two steps, one to mount the file in minikube, and then the kubernetes config needs to mount that volume internally. This will likely require a minor change or two to the Helm chart, probably conditional on some value so that deployed versions don't try to mount this nonexistent volume.

**Comment by hanzlamateen** [comment]
Used following approach to share host machine's upload folder in api pod.
https://stackoverflow.com/questions/48534980/mount-local-directory-into-pod-in-minikube

You will need to update your minikube values file to include:
```
api:
  fileServer:
    hostUploadFolder: "/hosthome/hanzlamateen/xrengine/packages/server/upload"
```
> Here `hanzlamateen/xrengine` corresponds to your xrengine repo in home folder.
