### ISSUE TITLE
[Story]:  Support multiple client connections per user

### ISSUE THREAD

**Issue by speigg** [XRFoundation/XREngine#7069]
We originally limited clients to one connection for these reasons:
- this is how Hubs did it
- we didn't have spectator mode
- to prevent people from spamming

However, there are some user experience issues that come about from the way we are limiting people to one client connection; namely:

- When someone clicks on a link to a location instance, it can sometimes open in an in-app browser (e.g., Discord does this); if the user then tries to open in the main browser app, there can be a race condition between these two connecting clients, and one will end up kicking the other 
- We eventually need/want to support multiple connection to faciliate the use of input fusion accross clients/devices; e.g., having one client that tracks full body pose, and another one that handles rendering and controller input. 
- This also allows a user to be connected in the editor at the same time as a location

## Stories

- [ ]  refactor the media/world servers to allow multiple client connections 
- [ ] allow one client to be the "main" client, and the others as spectators

**Comment by Suley** [comment]
Yes. We have same problem here. Especially when there is large amount of user. we have about 10% user reported this bug.
