### ISSUE TITLE
[Story] Projects can auto update when a specified branch is pushed to on github 

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#7103]

**Comment by HexaField** [comment]
https://github.com/marketplace/actions/github-repo-sync

**Comment by hanzlamateen** [comment]
From the discussion it seems like we can have an in house project update mechanism using kubernetes CronJob.
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/

We will need to maintain following additional information in project's table:
 - Source repo and branch
 - Auto update On/Off
 - Auto update schedule
 - Auto update user id (used to make Github api calls)
