### ISSUE TITLE
[Story] Integrate Avatar Upload with Avatar Select Menus

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#7246]
![Screenshot_from_2022-11-22_20-22-15](https://user-images.githubusercontent.com/10372036/203884976-b1d4faf1-5fbf-4453-b2d0-e21e14d7ebac.png)
![Screenshot_from_2022-11-22_20-21-22](https://user-images.githubusercontent.com/10372036/203884983-783ae508-eaa8-4652-b17b-561aa8671834.png)

- [ ] Infinite scroll of existing avatars with pagination
- [x] Can create new avatar from scratch & ReadyPlayer.Me
  - ReadyPlayer.Me iFrame replaces the whole menu
- [x] Integrate Edit Mode from Admin 
  - Once clicked, "Edit" button becomes "Save" which toggles fields being editable
- [x] Confirm button only visible when the selected avatar is different to the user's active avatar
- [x] The existing admin avatar edit drawer utilises the middle and right panels
- [ ] https://github.com/XRFoundation/XREngine/issues/7168

**Comment by montage125** [comment]
You want to let the user select avatar before entering for the first time
