### ISSUE TITLE
Git LFS support for projects

### ISSUE THREAD

**Issue by barankyle** [XRFoundation/XREngine#7341]
It would be nice to have large project assets stored in Git(Hub) LFS instead of in the main project repo.

https://git-lfs.github.com/
https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage

**Comment by speigg** [comment]
closed by https://github.com/XRFoundation/XREngine/commit/f1efe4a13e6c6347f1d5097c10a9a0ead1a5c12d
