### ISSUE TITLE
Optimize admin panel pagination & queries

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#7533]

**Comment by jerknose** [comment]
Turns out every module was being fed into initSystems at the routing level. I moved the avatar init to the avatar page.

I removed SceneClientModule, SceneCommonModule, TransformModule because I couldn't find a place were the data was needed.

Does anyone know if these modules are needed?

**Comment by HexaField** [comment]
> Turns out every module was being fed into initSystems at the routing level. I moved the avatar init to the avatar page.
> 
> I removed SceneClientModule, SceneCommonModule, TransformModule because I couldn't find a place were the data was needed.
> 
> Does anyone know if these modules are needed?

These are needed on the avatar page in order to render the avatar preview
