### ISSUE TITLE
[Feature] - VSCode Launcher - Dev Mode

### ISSUE THREAD

**Issue by jerknose** [XRFoundation/XREngine#7570]
Detangle npm run dev and launch all processes separately with one command.

**Comment by HexaField** [comment]
We have `npm run dev-tabs` which runs every process in a separate tab in terminal

**Comment by jerknose** [comment]
Ah... didn't see that one. I still prefer this way though. Which allows everything to stay within VSCode, enables full debugging  for each process, and requires no extra permissions or installs to run.

**Comment by speigg** [comment]
Very cool.
